apiVersion: v2
name: victoria-logs
description: A chart that combined victoria-logs-cluster and logs collector.

type: application

version: 0.0.1 # unused

appVersion: 0.0.1 # unused

dependencies:
  - name: victoria-logs-cluster
    version: 0.2.7
    repository: https://victoriametrics.github.io/helm-charts/
