# To skip enforcement for a specific pod, add the following label to the pod template:
#   metadata:
#     labels:
#       skip-container-resource-limit-vap: "true"
#
# Example in a Deployment:
#   spec:
#     template:
#       metadata:
#         labels:
#           skip-container-resource-limit-vap: "true"
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: require-resource-limits-for-all-containers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  variables:
    - name: all_containers
      expression: >-
        object.spec.containers +
        (has(object.spec.initContainers) ? object.spec.initContainers : []) +
        (has(object.spec.ephemeralContainers) ? object.spec.ephemeralContainers : [])
    - name: skip
      expression: >-
        has(object.metadata.labels) &&
        'skip-container-resource-limit-vap' in object.metadata.labels &&
        object.metadata.labels['skip-container-resource-limit-vap'] != 'false'
  validations:
    - expression: >-
        variables.skip ||
        variables.all_containers.all(c,
          has(c.resources) &&
          has(c.resources.limits) &&
          has(c.resources.limits.memory) &&
          has(c.resources.limits.cpu)
        )
      message: "All containers (incl. init and ephemeral) must define cpu and memory limits."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: require-resource-limits-for-all-containers-binding
spec:
  policyName: require-resource-limits-for-all-containers
  validationActions: ["Deny"]
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            {{- range .Values.vapContainerResourceLimits.excludedNamespaces }}
            - {{ . | quote }}
            {{- end }}
