apiVersion: v2
name: victoria-logs-single
description: >
  A wrapper chart for victoria-logs-single.
  It adds network policies. Once release containing
  https://github.com/VictoriaMetrics/operator/pull/2299
  is available and stable, we can drop the wrapper chart

type: application

version: 0.0.1 # unused

appVersion: 0.0.1 # unused

dependencies:
  - name: victoria-logs-single
    version: 0.13.8
    repository: "https://victoriametrics.github.io/helm-charts/"
