services:
  agent:
    volumes:
      - /docker/volumes/:/docker/volumes/

  dask-sidecar:
    deploy:
      placement:
        constraints:
          - node.role == worker

  clusters-keeper:
    deploy:
      replicas: 1

  static-webserver:
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"

  postgres:
    deploy:
      replicas: 0

  traefik:
    deploy:
      resources:
        limits:
          memory: 2048M

  payments:
    deploy:
      replicas: 1

  rabbit:
    deploy:
      labels:
        - traefik.tcp.services.rabbit.loadBalancer.server.port=5672
        - traefik.tcp.routers.rabbit.entrypoints=rabbitmq
        - traefik.tcp.routers.rabbit.tls=false
        - traefik.tcp.routers.rabbit.rule=ClientIP(`10.0.0.0/8`) || ClientIP(`172.16.0.0/12`) || ClientIP(`192.168.0.0/16`)
