services:
  autoscaling:
    deploy:
      replicas: 0
  postgres:
    labels:
      - "pgbackup.enable=true"
    deploy:
      placement:
        constraints:
          - node.labels.postgres==true
  datcore-adapter:
    deploy:
      replicas: 0
  resource-usage-tracker:
    deploy:
      replicas: 0
  static-webserver:
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
  traefik:
    deploy:
      labels:
        - prometheus-job=traefik_simcore_production
  wb-garbage-collector:
    hostname: "{{.Service.Name}}"
