version: '3.7'

services:

    adminer:
        deploy:
            replicas: 1

    db:
        deploy:
            replicas: 1

    api:
        deploy:
            resources:
                reservations:
                    cpus: "0"  # nih staging has not enough cpu
            replicas: 1
