version: '3.8'
services:
  mail:
    dns: # Sometimes the DNS from the AWS AMI are not properly copied into the container and the container cannot acces internet
      8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.traefik==true
          - node.labels.mail==true # mail server goes on the leader
      labels:
        - traefik.http.routers.mail.tls.certresolver=myresolver
