version: '3.8'
configs:
  self_signed_cert_mail_key.pem:
    file: ./../../certificates/domain.key
  self_signed_cert_mail_cert.pem:
    file: ./../../certificates/domain.crt
  self_signed_cert_cacert.pem:
    file: ./../../certificates/rootca.crt
services:
  mail:
    configs:
      - source: self_signed_cert_mail_key.pem
        target: /tmp/docker-mailserver/ssl/${SMTP_HOST}-key.pem
      - source: self_signed_cert_mail_cert.pem
        target: /tmp/docker-mailserver/ssl/${SMTP_HOST}-cert.pem
      - source: self_signed_cert_cacert.pem
        target: /tmp/docker-mailserver/ssl/demoCA/cacert.pem
    deploy:
      labels:
        - traefik.http.routers.mail.tls.certresolver=myresolver
