{
 "title": "[AWS] RDS (Databases) Metrics",
 "description": "Maintainer: YH\nOrigin: https://grafana.com/grafana/dashboards/15584-aws-rds/",
 "tags": [
  "cloudwatch",
  "rds",
  "db",
  "postgres"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "dbinstanceidentifier",
    "label": "DBInstanceIdentifier",
    "query": "dimension_values($region, AWS/RDS, CPUUtilization, DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  { "title": "CPUUtilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPUUtilization",
   "type": "timeseries",
   "description": "The percentage of CPU utilization.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DatabaseConnections/DiskQueueDepth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "DatabaseConnections",
   "type": "timeseries",
   "description": "The number of client network connections to the database instance.\n\nThe number of database sessions can be higher than the metric value because the metric value doesn't include the following:\n\n    - Sessions that no longer have a network connection but which the database hasn't cleaned up\n\n    - Sessions created by the database engine for its own purposes\n\n    - Sessions created by the database engine's parallel execution capabilities\n\n    - Sessions created by the database engine job scheduler\n\n    - Amazon RDS connections",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "DiskQueueDepth",
   "type": "timeseries",
   "description": "The number of outstanding I/Os (read/write requests) waiting to access the disk.\n\nThe number of database sessions can be higher than the metric value because the metric value doesn't include the following:\n\n    - Sessions that no longer have a network connection but which the database hasn't cleaned up\n\n    - Sessions created by the database engine for its own purposes\n\n    - Sessions created by the database engine's parallel execution capabilities\n\n    - Sessions created by the database engine job scheduler\n\n    - Amazon RDS connections",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "FreeableMemory/FreeStorageSpace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "FreeableMemory",
   "type": "timeseries",
   "description": "The amount of available random access memory.\n\nFor MariaDB, MySQL, Oracle, and PostgreSQL DB instances, this metric reports the value of the MemAvailable field of /proc/meminfo. ",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "FreeStorageSpace",
   "type": "timeseries",
   "description": "The amount of available storage space.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadIOPS/WriteIOPS/BurstBalance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "ReadIOPS",
   "type": "timeseries",
   "description": "The average number of disk read I/O operations per second.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "WriteIOPS",
   "type": "timeseries",
   "description": "The average number of disk write I/O operations per second.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BurstBalance",
   "type": "timeseries",
   "description": "The percent of General Purpose SSD (gp2) burst-bucket I/O credits available. ",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BurstBalance",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "ReadLatency/WriteLatency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "ReadLatency",
   "type": "timeseries",
   "description": "The average amount of time taken per disk I/O operation.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "WriteLatency",
   "type": "timeseries",
   "description": "The average amount of time taken per disk I/O operation.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "ReadThroughput/WriteThroughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "ReadThroughput",
   "type": "timeseries",
   "description": "The average number of bytes read from disk per second.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "WriteThroughput",
   "type": "timeseries",
   "description": "The average number of bytes written to disk per second.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkReceiveThroughput/NetworkTransmitThroughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 }
  },
  {
   "title": "NetworkReceiveThroughput",
   "type": "timeseries",
   "description": "The incoming (receive) network traffic on the DB instance, including both customer database traffic and Amazon RDS traffic used for monitoring and replication.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkTransmitThroughput",
   "type": "timeseries",
   "description": "The outgoing (transmit) network traffic on the DB instance, including both customer database traffic and Amazon RDS traffic used for monitoring and replication.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "SwapUsage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "SwapUsage",
   "type": "timeseries",
   "description": "The amount of swap space used on the DB instance. This metric is not available for SQL Server.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPUCreditUsage/CPUCreditBalance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 }
  },
  {
   "title": "CPUCreditUsage",
   "type": "timeseries",
   "description": "(T2 instances) The number of CPU credits spent by the instance for CPU utilization. One CPU credit equals one vCPU running at 100 percent utilization for one minute or an equivalent combination of vCPUs, utilization, and time. For example, you might have one vCPU running at 50 percent utilization for two minutes or two vCPUs running at 25 percent utilization for two minutes.\n\nCPU credit metrics are available at a five-minute frequency only. If you specify a period greater than five minutes, use the Sum statistic instead of the Average statistic.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPUCreditBalance",
   "type": "timeseries",
   "description": "(T2 instances) The number of earned CPU credits that an instance has accrued since it was launched or started. For T2 Standard, the CPUCreditBalance also includes the number of launch credits that have been accrued.\n\nCredits are accrued in the credit balance after they are earned, and removed from the credit balance when they are spent. The credit balance has a maximum limit, determined by the instance size. After the limit is reached, any new credits that are earned are discarded. For T2 Standard, launch credits don't count towards the limit.\n\nThe credits in the CPUCreditBalance are available for the instance to spend to burst beyond its baseline CPU utilization.\n\nWhen an instance is running, credits in the CPUCreditBalance don't expire. When the instance stops, the CPUCreditBalance does not persist, and all accrued credits are lost.\n\nCPU credit metrics are available at a five-minute frequency only.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MaximumUsedTransactionIDs/TransactionLogsGeneration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 }
  },
  {
   "title": "MaximumUsedTransactionIDs",
   "type": "timeseries",
   "description": "The maximum transaction IDs that have been used. Applies to PostgreSQL. ",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "MaximumUsedTransactionIDs",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "TransactionLogsGeneration",
   "type": "timeseries",
   "description": "The size of transaction logs generated per second. Applies to PostgreSQL.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{DBInstanceIdentifier}}",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TransactionLogsGeneration",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}