version: '3.7'
services:
  adminer:
    deploy:
      placement:
        constraints:
          - node.labels.ops==true
      resources:
        reservations:
          cpus: '0.0'  # not enough resources on master | YH Dec 2023
