version: '3.7'
services:
  adminer:
    dns: # Add this always for AWS, otherwise we get "No such image: " for docker services
      9.9.9.9
    deploy:
      placement:
        constraints:
          - node.labels.ops==true
