{{- $vectorLabels := .Values.vector.podLabels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vector-network-policy
spec:
  selector: >-
    app.kubernetes.io/instance == "{{ .Release.Name }}"
    && app.simcore.io/name == "{{ index $vectorLabels "app.simcore.io/name" }}"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ .Values.metricsPort }}
  egress:
    # Send logs to vmauth in victoria-logs namespace
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - 8427
    # Kubernetes API for kubernetes_logs source
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ .Values.kubernetesApiServerPort }}
