{
 "title": "SPARC DRC Metrics",
 "description": "SPARC DRC Metrics",
 "time": { "from": "now-3M", "to": "now" },
 "panels": [
  {
   "title": "Number of users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total number of registered users who have accounts on oSPARC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(production_total_number_of_users{deployment=\"pgsql\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of redirected anonymous users per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_name=\"webserver\", endpoint=\"/study/{id}\", simcore_user_agent!=\"puppeteer\"}[3h])*60*60*24) OR on() vector(0)",
     "legendFormat": "Avg number of redirected users"
    }
   ]
  },
  {
   "title": "Login rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average number of logins per month to oSPARC averaged over the quarter reported on",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint)  (rate(http_requests_total{endpoint=~\"/v0/me\", http_status=~\"2[0-9]+\", app_name=~\".+webserver\"}[30d]))*60*60*24*30",
     "legendFormat": "endpoint: {{endpoint}}"
    }
   ]
  },
  {
   "title": "Service and model usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average number of times per month a service on the oSPARC platform was ran, up to the top 20 most popular services averaged over the quarter reported on",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(topk(20, rate({__name__=~\"simcore_simcore_service_(director|webserver)_services_started_total:sum_by_service_key_service_tag\"}[30d])*60*60*24*30), \"service_name\", \"$3\", \"service_key\", \"simcore/services/(dynamic|comp)/([a-zA-Z0-9]*/)?(.*)\")",
     "legendFormat": "{{service_name}}:{{service_tag}}"
    }
   ]
  },
  {
   "title": "Data/Hardware usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall data storage that has been consumed over the quarter reported on",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=~\"/.*\", device!~'rootfs'} - node_filesystem_avail_bytes{mountpoint=~\"/.*\", device!~'rootfs'})",
     "legendFormat": "data usage"
    }
   ]
  },
  {
   "title": "Total CPU consumption over the quarter reported on [cpu-hours]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_cpu_seconds_total_v2:nonidle_increase_over_nodes_12weeks_v2"
    }
   ]
  }
 ]
}