{
 "title": "Production",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "storage 2XX req/sec/5min",
   "type": "graph",
   "description": "2XX requests per seconds in the last 5mins",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{endpoint=~\"/v0/.+\", http_status=~\"2[0-9]+\", instance=\"storage:8080\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "pg connections number",
   "type": "gauge",
   "description": "Current overall state of this backend. Possible values are:\nactive: The backend is executing a query.\n\nidle: The backend is waiting for a new client command.\n\nidle in transaction: The backend is in a transaction, but is not currently executing a query.\n\nidle in transaction (aborted): This state is similar to idle in transaction, except one of the statements in the transaction caused an error.\n\nfastpath function call: The backend is executing a fast-path function.\n\ndisabled: This state is reported if track_activities is disabled in this backend.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"simcoredb\", state!=\"disabled\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "webserver 2XX req/secs/5min",
   "type": "graph",
   "description": "2XX requests per second in the last 5mins for the webserver",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{endpoint=~\"/v0/.+\", http_status=~\"2[0-9]+\", instance=\"webserver:8080\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "up time of services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance!~\"postgres-.+\"}",
     "legendFormat": "{{instance}}"
    },
    { "expr": "pg_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Hits per published study",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "http_requests_total{endpoint=~\"/study/.+\", instance=\"webserver:8080\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}