version: "3.8"
services:
  ci-provisioned-ubuntu:
    image: ${DOCKER_REGISTRY:-itisfoundation}/${DOCKER_IMAGE_NAME:-ci-provisioned-ubuntu}:${DOCKER_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - local/${DOCKER_IMAGE_NAME:-ci-provisioned-ubuntu}:${DOCKER_IMAGE_TAG:-latest}
