{{- /* victoria-traces-single OTLP gRPC endpoint (same host as the Grafana datasource) */ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ index .Values "opentelemetry-collector" "configMap" "existingName" }}
  namespace: {{ .Release.Namespace }}
data:
  # key MUST be `relay` (required by opentelemetry-collector chart when using
  # standalone configMap
  relay: |
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:{{ .Values.otlpGrpcPortNumber }}
          http:
            endpoint: ${env:MY_POD_IP}:{{ .Values.otlpHttpPortNumber }}
    processors:
      batch:
        timeout: 5s
        send_batch_size: 8192
      filter/drop_healthcheck:
        error_mode: ignore
        traces:
          span:
            - attributes["http.route"] == "/health"
            - attributes["http.target"] == "/socket.io/"
            - attributes["url.path"] == "/socket.io/"
            - attributes["server.address"] == "/var/run/docker.sock"
            - IsMatch(attributes["server.address"], "^monitoring..*")
            - attributes["net.peer.name"] == "/var/run/docker.sock"
            - attributes["http.route"] == "healthcheck_readiness_probe"
            - attributes["http.route"] == "healthcheck_liveness_probe"
            - attributes["http.target"] == "/metrics" and IsMatch(attributes["http.user_agent"], ".*Prometheus.*") == true
            - attributes["db.statement"] == "PING" and attributes["db.system"] == "redis"
            - IsMatch(attributes["db.statement"], "^SCAN[\\s?]*$") and attributes["db.system"] == "redis"
    exporters:
      otlp_grpc:
        endpoint: {{ include "tracing-stack.vtHost" . }}:{{ .Values.otlpGrpcPortNumber }}
        tls:
          insecure: true
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, filter/drop_healthcheck]
          exporters: [otlp_grpc]
      telemetry:
        metrics:
          # https://opentelemetry.io/docs/collector/internal-telemetry/#prometheus-endpoint-for-internal-metrics
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: '${env:MY_POD_IP}'
                    port: {{ .Values.otelMetricsPortNumber }}
        logs:
          level: warn
