{{- $pathPrefix := index .Values "victoria-traces-single" "server" "extraArgs" "http.pathPrefix" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-victoria-traces-internal
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 }}
    app.kubernetes.io/instance: {{ .Release.Name | trunc 63 }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: webinternal
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.basicAuthMiddleware | quote }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.internalIngressHost | quote }}
      http:
        paths:
          - path: {{ printf "%s/insert/opentelemetry/v1/traces" $pathPrefix | quote }}
            pathType: Exact
            backend:
              service:
                name: {{ index .Values "victoria-traces-single" "server" "fullnameOverride" }}
                port:
                  number: {{ .Values.victoriaTracesHttpPortNumber }}
