{
 "title": "Services",
 "description": "Maintainer: MB",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "query": "__DS_TYPE__" },
   {
    "name": "service",
    "label": "simcore service",
    "query": "agent, api-server, autoscaling, catalog, clusters-keeper, datcore-adapter, director, director-v2, dynamic-schdlr, invitations, payments, resource-usage-tracker, storage, wb-api-server, webserver, wb-auth, wb-db-event-listener, wb-garbage-collector\n"
   },
   { "name": "deployment", "label": "deployment", "query": "staging, production, master" }
  ]
 },
 "panels": [
  { "title": "Resource utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"${deployment}-simcore_${deployment}_${service}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throttled CPU Time Rate (seconds/second)",
   "type": "timeseries",
   "description": "Maintainer: MB",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container_label_com_docker_swarm_service_name=~\"${deployment}-simcore_${deployment}_${service}\"}[$__rate_interval])",
     "legendFormat": "{{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Maintainer: MB",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"${deployment}-simcore_${deployment}_${service}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Asyncio  event loop lag per container IP",
   "type": "timeseries",
   "description": "Time between scheduling and execution of event loop callbacks. >10ms consistently indicates event loop saturation.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "asyncio_event_loop_lag_seconds{service_name=\"$service\", deployment=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total number of tasks in the asyncio event loop per container IP",
   "type": "timeseries",
   "description": "Note that this metric contains both tasks which are done and tasks which are cancelled.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "asyncio_event_loop_tasks{service_name=\"$service\", deployment=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service logs",
   "type": "logs",
   "description": "Service logs. N.B. info-level health check and metrics logs are removed. Maintainer: MB.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".*$deployment.*$service.*\"} | json | message !~ `.*log_level=INFO.*GET / HTTP.*` | message !~ `.*log_level=INFO.*GET /metrics HTTP.*` | line_format `{{.log_msg}}`"
    }
   ]
  },
  { "title": "HTTP server metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "HTTP request duration heatmap",
   "type": "heatmap",
   "description": "Each temporal slice can be thought of as a histogram of request durations",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by(le) (increase(http_request_latency_seconds_with_labels_bucket{job=\"simcore\", service_name=\"$service\", deployment=\"$deployment\", endpoint!=\"/socket.io/\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP requests in progress per container IP",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by(instance) (http_in_flight_requests{service_name=\"$service\", deployment=\"$deployment\", endpoint!=\"/socket.io/\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg HTTP request duration (over last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(endpoint, method) (increase(http_request_latency_seconds_with_labels_sum{service_name=\"$service\", deployment=\"$deployment\", endpoint!=\"/socket.io/\"}[5m])) / sum by(endpoint, method) (increase(http_request_latency_seconds_with_labels_count{service_name=\"$service\", deployment=\"$deployment\", endpoint!=\"/socket.io/\"}[5m]))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP requests count per HTTP status (last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum by(http_status) (increase(http_requests_total{job=\"simcore\", service_name=\"$service\", deployment=\"$deployment\"}[5m]))",
     "legendFormat": "http_status={{http_status}}"
    }
   ]
  },
  {
   "title": "HTTP request count per endpoint (last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "sum by(endpoint, method) (increase(http_request_latency_seconds_with_labels_count{service_name=\"$service\", deployment=\"$deployment\"}[5m]))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  { "title": "RPC server metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "RPC request duration heatmap",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ span.messaging.system=\"rabbitmq\" && span.messaging.operation=\"receive\" && span.messaging.destination=~\"^${deployment}_${service}\\\\..*\"} | histogram_over_time(duration)",
     "tableType": "traces"
    },
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ span.messaging.system=\"rabbitmq\" && span.messaging.operation=\"receive\" && span.messaging.destination=~\"^${service}\\\\..*\"} | histogram_over_time(duration)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Avg RPC request duration (over last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ span.messaging.system=\"rabbitmq\" && span.messaging.operation=\"receive\" && span.messaging.destination=~\"^${deployment}_${service}\\\\..*\"} | avg_over_time(duration) by (span.messaging.destination)",
     "tableType": "spans"
    },
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ span.messaging.system=\"rabbitmq\" && span.messaging.operation=\"receive\" && span.messaging.destination=~\"^${service}\\\\..*\"} | avg_over_time(duration) by (span.messaging.destination)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Sampled RPC Request Count per Endpoint (last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 160 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ span.messaging.system=\"rabbitmq\" && span.messaging.operation=\"receive\" && span.messaging.destination=~\"^${deployment}_${service}\\\\..*\"} | count_over_time() by (span.messaging.destination)",
     "tableType": "spans"
    },
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ span.messaging.system=\"rabbitmq\" && span.messaging.operation=\"receive\" && span.messaging.destination=~\"^${service}\\\\..*\"} | count_over_time() by (span.messaging.destination)",
     "tableType": "traces"
    }
   ]
  }
 ]
}