#!/bin/bash
# die on non 0 exit code
set -e

FOLDER_CHECKS=(deployment-agent/ .travis.yml)

before_install() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        bash ops/travis/helpers/install_docker_compose
        bash ops/travis/helpers/show_system_versions
    fi
}

install() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        pip install --upgrade pip==19.0.3 wheel setuptools && pip3 --version
        pushd services/deployment-agent; pip3 install -r requirements/dev.txt; popd
        pushd services/deployment-agent; pip3 install -r tests/requirements.txt; popd
    fi
}

before_script() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        pip freeze
        docker images
    fi
}

script() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        pytest --cov-append --cov=simcore_service_deployment_agent -v services/deployment-agent/tests
    else
        echo "No changes detected. Skipping unit-testing of deployment-agent."
    fi
}

after_success() {
    if bash ops/travis/helpers/test_for_changes "${FOLDER_CHECKS[@]}";
    then
        coveralls
    fi
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
