#!/bin/bash

set -e

FOLDER_CHECKS="deployment-agent\/"

before_install() {
    if [ -n "$(bash ops/travis/helpers/test_for_changes deployment-agent)" ];
    then
        bash ops/travis/helpers/install_docker_compose
        bash ops/travis/helpers/show_system_versions
    fi
}

install() {
    if [ -n "$(bash ops/travis/helpers/test_for_changes deployment-agent)" ];
    then
        pip install --upgrade pip wheel setuptools && pip3 --version
        pushd services/deployment-agent; pip3 install -r requirements/dev.txt; popd
    fi
}

before_script() {
    if [ -n "$(bash ops/travis/helpers/test_for_changes deployment-agent)" ];
    then
        pip freeze
        docker images
    fi
}

script() {
    if [ -n "$(bash ops/travis/helpers/test_for_changes deployment-agent)" ];
    then
        pytest --cov=simcore_service_deployment_agent -v services/deployment-agent/tests
    else
        echo "No changes detected. Skipping unit-testing of deployment-agent."
    fi
}

after_success() {
    if [ -n "$(bash ops/travis/helpers/test_for_changes deployment-agent)" ];
    then
        coveralls
    fi
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
