{{- $cluster := index .Values "victoria-logs-cluster" }}
{{- $selectPort := trimPrefix ":" (index $cluster.vlselect.http 0).value }}
{{- $storagePort := trimPrefix ":" (index $cluster.vlstorage.http 0).value }}
{{- $selectLabels := $cluster.vlselect.podLabels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vlselect-network-policy
spec:
  selector: >-
    app.kubernetes.io/instance == "{{ .Release.Name }}"
    && app.simcore.io/name == "{{ index $selectLabels "app.simcore.io/name" }}"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $selectPort }}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $storagePort }}
