{{- $logs := index .Values "victoria-logs-cluster" }}
{{- $selectPort := trimPrefix ":" (index $logs.vlselect.http 0).value }}
{{- $storagePort := trimPrefix ":" (index $logs.vlstorage.http 0).value }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vlselect-network-policy
spec:
  selector: >-
    app.kubernetes.io/instance == "{{ .Release.Name }}"
    && app.kubernetes.io/name == "victoria-logs-cluster"
    && app == "vlselect"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $selectPort }}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $storagePort }}
    - action: Allow
      protocol: UDP
      destination:
        ports:
          - 53
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - 53
