{{- $cluster := index .Values "victoria-logs-cluster" }}
{{- $vmauthPort := trimPrefix ":" (index $cluster.vmauth.http 0).value }}
{{- $insertPort := trimPrefix ":" (index $cluster.vlinsert.http 0).value }}
{{- $selectPort := trimPrefix ":" (index $cluster.vlselect.http 0).value }}
{{- $vmauthLabels := $cluster.vmauth.podLabels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmauth-network-policy
spec:
  selector: >-
    app.kubernetes.io/instance == "{{ .Release.Name }}"
    && app.simcore.io/name == "{{ index $vmauthLabels "app.simcore.io/name" }}"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $vmauthPort }}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $insertPort }}
          - {{ $selectPort }}
