apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "aws-ebs-csi-driver" "awsAccessSecret" "name" }}
  namespace: {{ .Release.Namespace }} # must be in the same namespace as ebs csi driver deployment
type: Opaque
stringData:
  {{ index .Values "aws-ebs-csi-driver" "awsAccessSecret" "keyId" }}: {{ .Values.awsCredentials.accessKeyId | quote }}
  {{ index .Values "aws-ebs-csi-driver" "awsAccessSecret" "accessKey" }}: {{ .Values.awsCredentials.secretAccessKey | quote }}
