apiVersion: v2
name: vector
description: >-
  A wrapper around vector

type: application

version: &vectorChartVersion 0.56.0 # unused

appVersion: 0.0.1 # unused

dependencies:
  - name: vector
    version: *vectorChartVersion
    repository: https://helm.vector.dev
