{{- $cluster := index .Values "victoria-logs-cluster" }}
{{- $insertPort := trimPrefix ":" (index $cluster.vlinsert.http 0).value }}
{{- $storagePort := trimPrefix ":" (index $cluster.vlstorage.http 0).value }}
{{- $insertLabels := $cluster.vlinsert.podLabels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vlinsert-network-policy
spec:
  selector: >-
    app.kubernetes.io/instance == "{{ .Release.Name }}"
    && app.simcore.io/name == "{{ index $insertLabels "app.simcore.io/name" }}"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $insertPort }}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $storagePort }}
