{{- $cluster := index .Values "victoria-logs-cluster" }}
{{- $storagePort := trimPrefix ":" (index $cluster.vlstorage.http 0).value }}
{{- $storageLabels := $cluster.vlstorage.podLabels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vlstorage-network-policy
spec:
  selector: >-
    app.kubernetes.io/instance == "{{ .Release.Name }}"
    && app.simcore.io/name == "{{ index $storageLabels "app.simcore.io/name" }}"
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $storagePort }}
