#!/bin/bash
# as of http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

before_install() {
    bash ops/travis/helpers/install_docker_compose
    bash ops/travis/helpers/show_system_versions
}

install() {
    pip3 install --upgrade pip wheel setuptools && pip3 --version
    pip3 install -r ops/travis/system-testing/requirements.txt
    make build
}

before_script() {
    pip freeze
    docker images
    make up
    docker service ls
}

script() {
    # wait for a minute to let the swarm warm up...
    pytest --cov-append --cov=simcore_service_deployment_agent -v ops/travis/system-testing/tests
}

after_success() {
    make down
}

after_failure() {
    docker service ls
    docker service ps portainer_auto-deployment-agent
    docker service logs portainer_auto-deployment-agent
    docker ps
    make down
}

# Check if the function exists (bash specific)
if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi
