{
 "title": "S4l-chatbox-dashboard",
 "description": "Maintainer: MB",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "query": "__DS_TYPE__" }
  ]
 },
 "panels": [
  {
   "title": "Total number of questions asked",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(number_of_questions_asked)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Percentage of total judged answers per score",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(score) (number_of_judged_answers) / ignoring(score) group_left sum (number_of_judged_answers)",
     "legendFormat": "{{score}}"
    }
   ]
  },
  {
   "title": "Average request duration over last 5min",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method, handler) (increase(http_request_duration_seconds_sum{job=\"vendor_chat_backend\"}[5m])) / sum by(handler, method) (increase(http_request_duration_seconds_count{job=\"vendor_chat_backend\"}[5m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  }
 ]
}