logs:
  general:
    level: DEBUG
  access:
    enabled: true

service:
  type: NodePort

deployment:
  healthchecksPort: 8000  # same as `web` port used by `ping` healthcheck

ports:
  web:
    port: 8000
    nodePort: 32080
  websecure:
    nodePort: 32443

additionalArguments:
  - "--ping=true"
  - "--ping.entrypoint=web"
