apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    # deleting traefik namespace has an important side effect.
    # it requires re-issuance of certificates and might cause rate-limits
    # if done many times https://letsencrypt.org/docs/rate-limits/#certificate-issuance-limits
    # Note: this does not prevent deletion of secret with cert and key. Certificate must be re-issued
    # TIP 1: for testing use let's encrypt staging environment or self-signed issuers
    # TIP 2: backup secrets before deleting the namespace to avoid re-issuance of certificates
    - osparc-ops.io/tls-certificate-reissue-rate-limit-protection
spec:
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  secretName: {{ .Values.certificate.secretName }}
  dnsNames:
{{- range .Values.certificate.dnsNames }}
    - {{ . | quote }}
{{- end }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
