apiVersion: v2
name: victoria-metrics-k8s-stack
description: A Helm chart for Kubernetes
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: &vmK8sStackChartVersion 0.82.0

# This is the version number of the application being deployed.
appVersion: "1.145.0"

dependencies:
  - name: victoria-metrics-k8s-stack
    version: *vmK8sStackChartVersion
    # avoid '-' for simplicity (see link below)
    # https://stackoverflow.com/questions/63853679/helm-templating-doesnt-let-me-use-dash-in-names
    alias: vm-k8s-stack
    repository: "https://victoriametrics.github.io/helm-charts/"
