# CI-only stub for Trivy chart scanning.

repositories:
  - name: jetstack # cert-manager
    url: https://charts.jetstack.io
  - name: traefik
    url: https://traefik.github.io/charts
  - name: aws-ebs-csi-driver
    url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
---
environments:
  default:
    values:
      - ebsStorageClassName: "ebs-sc"
      - grafanaVictoriaMetricsDatasourceUid: "P4169E755C3094E38"
      - longhornStorageClassName: "longhorn"
      - topolvmStorageClassName: "topolvm"
---
releases:
  - name: security-hardening
    chart: ./security-hardening
    namespace: kube-system
    values:
      - security-hardening/values.yaml

  - name: cert-manager
    chart: ./cert-manager
    namespace: cert-manager
    values:
      - cert-manager/values.common.yaml.gotmpl
      - cert-manager/values.selfsigned.yaml.gotmpl

  - name: traefik
    chart: ./traefik
    namespace: traefik
    needs:
      - cert-manager/cert-manager
    values:
      - traefik/values.common.yaml.gotmpl

  - name: aws-ebs-csi-driver
    chart: ./aws-ebs-csi-driver
    namespace: aws-ebs-csi-driver
    values:
      - aws-ebs-csi-driver/values.yaml.gotmpl
