{
 "title": "Requests load overview",
 "description": "Maintainer: SAN.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "__DS_TYPE__" }
  ]
 },
 "panels": [
  {
   "title": "Active Users according to redis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_key_value{key=~\".+:alive\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "OPS Traefik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Up time",
   "type": "table",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "label_replace(\n  time() - sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}) by (name),\n  \"replica\", \"$1\", \"name\", \"^traefik_traefik\\\\.(\\\\d+)\\\\..*$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}[$__rate_interval])) by (name, instance) * 100",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}) * 100",
     "legendFormat": "CPU limit"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=\"traefik_traefik\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}[1m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=\"traefik_traefik\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  {
   "title": "Incoming requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{job=\"traefik_ops\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{job=\"traefik_ops\", protocol=\"http\"}) / sum(traefik_entrypoint_requests_total{job=\"traefik_ops\", protocol=\"http\"}) * 1000",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Simcore Traefik",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{job=\"traefik_ops\", service=~\".+-simcore_.+@swarm\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{job=\"traefik_ops\", protocol=\"http\", service=~\".+-simcore_.+@swarm\"}) / sum(traefik_entrypoint_requests_total{job=\"traefik_ops\", protocol=\"http\"}) * 1000",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}[5m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=\"traefik_traefik\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}[15m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=\"traefik_traefik\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=\"traefik_traefik\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  { "title": "Simcore Traefik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Up time",
   "type": "table",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(\n  time() - sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}) by (name),\n  \"replica\", \"$1\", \"name\", \"^.+\\\\.(\\\\d+)\\\\..*$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}[$__rate_interval])) by (name, instance) * 100",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}) * 100",
     "legendFormat": "CPU limit"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}[1m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service_name=\"traefik\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service_name=\"traefik\", protocol=\"http\"}) / sum(traefik_entrypoint_requests_total{service_name=\"traefik\", protocol=\"http\"}) * 1000",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Webserver",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service_name=\"traefik\", service=~\".+-simcore_webserver.*@swarm\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service_name=\"traefik\", protocol=\"http\", service=~\".+-simcore_webserver.*@swarm\"}) / sum(traefik_entrypoint_requests_total{service_name=\"traefik\", protocol=\"http\"}) * 1000",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}[5m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  {
   "title": "API-server",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service_name=\"traefik\", service=~\".+-simcore_api-server.*@swarm\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service_name=\"traefik\", protocol=\"http\", service=~\".+-simcore_api-server.*@swarm\"}) / sum(traefik_entrypoint_requests_total{service_name=\"traefik\", protocol=\"http\"}) * 1000",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}[15m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_traefik\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  {
   "title": "Static Webserver",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service_name=\"traefik\", service=~\".+-simcore_static_webserver.*@swarm\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service_name=\"traefik\", protocol=\"http\", service=~\".+-simcore_static_webserver.*@swarm\"}) / sum(traefik_entrypoint_requests_total{service_name=\"traefik\", protocol=\"http\"}) * 1000",
     "legendFormat": "Avg response time"
    }
   ]
  },
  { "title": "Webserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Up time",
   "type": "table",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "label_replace(\n  time() - sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}) by (name),\n  \"replica\", \"$1\", \"name\", \"^.+\\\\.(\\\\d+)\\\\..*$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}[$__rate_interval])) by (name, instance) * 100",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}) * 100",
     "legendFormat": "CPU limit"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}[1m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_name=\"webserver\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(http_request_latency_seconds_with_labels_sum{service_name=\"webserver\", endpoint!~\"/socket.io/\"}) / sum(http_request_latency_seconds_with_labels_count{service_name=\"webserver\", endpoint!~\"/socket.io/\"})",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Docker Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}[$__rate_interval]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}[$__rate_interval]))",
     "legendFormat": "Transmiting"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}[5m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}[15m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_webserver\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  { "title": "API-Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Up time",
   "type": "table",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "label_replace(\n  time() - sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}) by (name),\n  \"replica\", \"$1\", \"name\", \"^.+\\\\.(\\\\d+)\\\\..*$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 2, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}[$__rate_interval])) by (name, instance) * 100",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}) * 100",
     "legendFormat": "CPU limit"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}[1m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_name=\"api-server\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(http_request_latency_seconds_with_labels_sum{service_name=\"api-server\", endpoint!~\"/socket.io/\"}) / sum(http_request_latency_seconds_with_labels_count{service_name=\"api-server\", endpoint!~\"/socket.io/\"})",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Docker Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}[$__rate_interval]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}[$__rate_interval]))",
     "legendFormat": "Transmiting"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}[5m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}[15m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_api-server\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  { "title": "API-WB-Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Up time",
   "type": "table",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "label_replace(\n  time() - sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}) by (name),\n  \"replica\", \"$1\", \"name\", \"^.+\\\\.(\\\\d+)\\\\..*$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 2, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}[$__rate_interval])) by (name, instance) * 100",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}) * 100",
     "legendFormat": "CPU limit"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}[1m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_name=\"wb-api-server\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(http_request_latency_seconds_with_labels_sum{service_name=\"wb-api-server\", endpoint!~\"/socket.io/\"}) / sum(http_request_latency_seconds_with_labels_count{service_name=\"wb-api-server\", endpoint!~\"/socket.io/\"})",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Docker Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}[$__rate_interval]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}[$__rate_interval]))",
     "legendFormat": "Transmiting"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}[5m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}[15m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-api-server\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  { "title": "Auth Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Up time",
   "type": "table",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "label_replace(\n  time() - sum(container_start_time_seconds{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}) by (name),\n  \"replica\", \"$1\", \"name\", \"^.+\\\\.(\\\\d+)\\\\..*$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 2, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}[$__rate_interval])) by (name, instance) * 100",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}) * 100",
     "legendFormat": "CPU limit"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}",
     "legendFormat": "{{instance}}: {{name}}"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Load1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}[1m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_name=\"wb-auth\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(http_request_latency_seconds_with_labels_sum{service_name=\"wb-auth\", endpoint!~\"/socket.io/\"}) / sum(http_request_latency_seconds_with_labels_count{service_name=\"wb-auth\", endpoint!~\"/socket.io/\"})",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Docker Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}[$__rate_interval]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}[$__rate_interval]))",
     "legendFormat": "Transmiting"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}[5m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}[15m])) / sum(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"}/container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\".+-simcore_.+_wb-auth\"})",
     "legendFormat": "{{instance}}: {{name}}"
    }
   ]
  }
 ]
}