{
 "title": "[AWS] (ElastiCache) Redis Overview",
 "description": "Maintainer: YH\nOrigin: https://grafana.com/grafana/dashboards/969-aws-elasticache-redis/",
 "tags": [
  "cloudwatch",
  "redis",
  "db"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "cacheclusterId",
    "label": "CacheClusterId",
    "query": "dimension_values($region,AWS/ElastiCache,CPUUtilization,CacheClusterId)"
   },
   {
    "name": "cachenodeid",
    "label": "CacheNodeId",
    "query": "dimension_values($region,AWS/ElastiCache,CPUUtilization,CacheNodeId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Evictions",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Reclaimed",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cmds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "GetTypeCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HashBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ListBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SetBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SetTypeCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SortedSetBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "StringBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NewConnections",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SaveInProgress / CurrItems",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SaveInProgress",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CurrItems",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesUsedForCache / ReplicationBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReplicationBytes",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HyperLogLogBasedCmds / ReplicationLag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HyperLogLogBasedCmds",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReplicationLag",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid DatabaseMemoryUsagePercentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid CPUUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid EngineCPUUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "EngineCPUUtilization",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid NetworkBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid FreeableMemory / SwapUsage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SwapUsage",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "CacheClusterId": "$cacheclusterId", "CacheNodeId": "$cachenodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 77 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheMetrics.html\">AWS CloudWatch ElastiCache documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/969\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}