environments:
  default:
    values:
      - helmfile_environment.yaml

---

helmDefaults:
  # wait for all resources to be ready before marking the release as successful
  # this makes sure that releases are properly installed before continuing with
  # dependent (via `needs`) releases. Read more via `helm install --help`
  wait: true
  waitForJobs: true
  timeout: 600

  # avoid errors on first installation
  # passes --disable-validation to helm 3 diff plugin
  disableValidation: true
