version: "3.7"
services:
  redis-commander:
    image: rediscommander/redis-commander:snyk-fix-1841981ea4b1abcbc4c13e21d5d2997d
    init: true
    ports:
      - 8081
    networks:
      - monitored
      - public
    environment:
      - >-
        REDIS_HOSTS=
        resources:${REDIS_HOST}:${REDIS_PORT}:0:${REDIS_PASSWORD},
        locks:${REDIS_HOST}:${REDIS_PORT}:1:${REDIS_PASSWORD},
        validation_codes:${REDIS_HOST}:${REDIS_PORT}:2:${REDIS_PASSWORD},
        scheduled_maintenance:${REDIS_HOST}:${REDIS_PORT}:3:${REDIS_PASSWORD},
        user_notifications:${REDIS_HOST}:${REDIS_PORT}:4:${REDIS_PASSWORD},
        announcements:${REDIS_HOST}:${REDIS_PORT}:5:${REDIS_PASSWORD},
        distributed_identifiers:${REDIS_HOST}:${REDIS_PORT}:6:${REDIS_PASSWORD},
        deferred_tasks:${REDIS_HOST}:${REDIS_PORT}:7:${REDIS_PASSWORD}
      - URL_PREFIX=/redis
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${PUBLIC_NETWORK}
        - traefik.http.services.redis.loadbalancer.server.port=8081
        - traefik.http.routers.redis.rule=Host(`${MONITORING_DOMAIN}`) && PathPrefix(`/redis`)
        - traefik.http.routers.redis.entrypoints=https
        - traefik.http.routers.redis.tls=true
        - traefik.http.middlewares.redis_stripprefixregex.stripprefixregex.regex=^/redis
        - traefik.http.routers.redis.middlewares=ops_auth@swarm, ops_gzip@swarm, ops_whitelist_ips@swarm
      resources:
        limits:
          memory: 192M
          cpus: "0.5"
        reservations:
          memory: 64M
          cpus: "0.1"

networks:
  public:
    external: true
    name: ${PUBLIC_NETWORK}
  monitored:
    name: ${MONITORED_NETWORK}
    external: true
