# Source: https://docs.tigera.io/calico/3.30/network-policy/get-started/kubernetes-default-deny
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-global-deny-network-policy
spec:
  # "kube-public", "kube-system", "kube-node-lease" -- system namespaces
  # "calico-system", "calico-apiserver", "tigera-operator" -- calico namespaces (when installed via scripts [local deployment])
  # TODO: other namespaces are to be removed from this list (once appropriate network policies are created)
  namespaceSelector:
    kubernetes.io/metadata.name not in {"kube-public", "kube-system", "kube-node-lease", "calico-system", "calico-apiserver", "tigera-operator", "reflector", "traefik", "victoria-logs", "csi-s3", "portainer", "topolvm", "local-path-storage", "longhorn"}
  types:
    - Ingress
    - Egress
  egress:
    # allow all namespaces to communicate to DNS pods
    # this will also apply to pods that have network policy defined
    # so that we don't need to define DNS policy for each pod
    - action: Allow
      protocol: UDP
      destination:
        selector: 'k8s-app == "kube-dns"'
        ports:
          - 53
    # nodelocaldns: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/README.md#nodelocal-dns-cache
    # IP from https://github.com/kubernetes-sigs/kubespray/blob/v2.24.1/roles/kubespray-defaults/defaults/main/main.yml#L108
    - action: Allow
      protocol: UDP
      nets:
        - 169.254.25.10/32
      ports:
        - 53
    - action: Allow
      protocol: TCP
      destination:
        selector: 'k8s-app == "kube-dns"'
        ports:
          - 53
    - action: Allow
      protocol: TCP
      nets:
        - 169.254.25.10/32
      ports:
        - 53
