version: '3.7'
services:
  mongodb:
    deploy:
      placement:
        constraints:
          - node.labels.graylog==true
  elasticsearch:
    deploy:
      placement:
        constraints:
          - node.labels.graylog==true
  graylog:
    dns:
      8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.graylog==true
