services:
  traefik:
    networks:
      public:
      monitored:
        aliases: # This enables the registry to resolve "registry.osparc.local" etc. to minio, via traefik. Necessary to give the registry access to the S3 bucket.
          - "${STORAGE_DOMAIN}"
          - "${REGISTRY_DOMAIN}"
          - "${MONITORING_DOMAIN}"
    deploy:
      placement:
        constraints: []
    env_file:
      - .env
    configs:
      - source: traefik_dynamic_config.yml
        target: /etc/traefik/dynamic_conf.yml
      - source: customEntrypoint.sh
        target: /customEntrypoint.sh
    secrets:
      - source: domain.key
        target: /etc/traefik_certs/osparc.local.key
      - source: domain.crt
        target: /etc/traefik_certs/osparc.local.crt
      - source: storageca.crt
        target: /secrets/storageca.crt

configs:
  traefik_dynamic_config.yml:
    file: ./traefik_dynamic_config.yml
  customEntrypoint.sh:
    file: ./config/customCAInit.sh

secrets:
  domain.key:
    external: true
  domain.crt:
    external: true
  storageca.crt:
    external: true
