version: "3.7"

services:
  traefik:
    command:
      # Here we subsitute with a custom entrypoint to load self-signed
      # certificates.
      - "/bin/sh"
      - "/customEntrypoint.sh"
      - "--api=true"
      - "--api.dashboard=true"
      - "--log.level=${OPS_TRAEFIK_LOGLEVEL}"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.names.ClientUsername=keep"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--accesslog.fields.headers.names.User-Agent=keep"
      - "--accesslog.fields.headers.names.Authorization=drop"
      - "--accesslog.fields.headers.names.Content-Type=keep"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.smtp.address=:25"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.transport.respondingTimeouts.idleTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.http.transport.respondingTimeouts.writeTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.http.transport.respondingTimeouts.readTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.https.address=:443"
      - "--entryPoints.https.transport.respondingTimeouts.idleTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.https.transport.respondingTimeouts.writeTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.https.transport.respondingTimeouts.readTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.postgres.address=:5432"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.http.http.redirections.entrypoint.permanent=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedByDefault=false"
      - "--providers.swarm.constraints=!LabelRegex(`io.simcore.zone`, `${TRAEFIK_SIMCORE_ZONE}`)"
      - "--core.defaultRuleSyntax=v2"
      - "--tracing.serviceName=ops-traefik"
      - "--tracing.otlp.http.endpoint=http://otel-collector:4318/v1/traces"
      - "--providers.file.directory=/etc/traefik/"
      - "--providers.file.watch=true"
    networks:
      public:
      monitored:
        aliases: # This enables the registry to resolve "registry.osparc.local" etc. to minio, via traefik. Necessary to give the registry access to the S3 bucket.
          - "${STORAGE_DOMAIN}"
          - "${REGISTRY_DOMAIN}"
          - "${MONITORING_DOMAIN}"
    deploy:
      placement:
        constraints: []
    env_file:
      - .env
    configs:
      - source: traefik_dynamic_config.yml
        target: /etc/traefik/dynamic_conf.yml
      - source: customEntrypoint.sh
        target: /customEntrypoint.sh
    secrets:
      - domain.key
      - domain.crt
      - source: storageca.crt
        target: /secrets/storageca.crt

configs:
  traefik_dynamic_config.yml:
    file: ./traefik_dynamic_config.yml
  customEntrypoint.sh:
    file: ./config/customCAInit.sh

secrets:
  domain.key:
    external: true
  domain.crt:
    external: true
  storageca.crt:
    external: true
