version: '3.7'
services:
  traefik:
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--log.level=${OPS_TRAEFIK_LOGLEVEL}'
      #   - '--accesslog=true'
      - '--metrics.prometheus=true'
      - '--metrics.prometheus.addEntryPointsLabels=true'
      - '--metrics.prometheus.addServicesLabels=true'
      - '--entryPoints.metrics.address=:8082'
      - '--metrics.prometheus.entryPoint=metrics'
      - '--entryPoints.http.address=:80'
      - '--entryPoints.https.address=:443'
      - '--entryPoints.master_postgres.address=:5432'
      - '--entryPoints.smtp.address=:25'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.swarmMode=true'
      - '--providers.docker.exposedByDefault=false'
      - '--tracing=true'
      - '--tracing.jaeger=true'
      - '--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling'
      - '--tracing.jaeger.localAgentHostPort=jaeger:6831'
      - '--providers.docker.constraints=!LabelRegex(`io.simcore.zone`, `.+`)'
      - '--entryPoints.https.forwardedHeaders.insecure'
      - '--providers.file.directory=/etc/traefik/'
      - '--providers.file.watch=true'
    env_file:
      - .env
    configs:
      - source: traefik_dynamic_config.yml
        target: /etc/traefik/dynamic_conf.yml
    deploy:
      placement:
        constraints:
          - node.labels.traefik==true
    volumes:
    - /etc/traefik_certs:/etc/traefik_certs

configs:
  traefik_dynamic_config.yml:
    file: ./config/osparc-master.speag.com_dyn_cfg.yaml
