version: "3.7"
services:
  traefik:
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--log.level=${OPS_TRAEFIK_LOGLEVEL}"
      - "--accesslog=false"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.http.http.redirections.entrypoint.permanent=true"
      - "--entryPoints.http.transport.respondingTimeouts.idleTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.http.transport.respondingTimeouts.writeTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.http.transport.respondingTimeouts.readTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.https.address=:443"
      - "--entryPoints.https.transport.respondingTimeouts.idleTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.https.transport.respondingTimeouts.writeTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.https.transport.respondingTimeouts.readTimeout=21600s" #6h, for https://github.com/traefik/traefik/issues/10805
      - "--entryPoints.smtp.address=:25"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedByDefault=false"
      - "--core.defaultRuleSyntax=v2"
      - "--tracing=true"
      - "--tracing.addinternals"
      - "--tracing.otlp=true"
      - "--tracing.otlp.http=true"
      - "--providers.swarm.constraints=!LabelRegex(`io.simcore.zone`, `.+`)"
      - "--entryPoints.https.forwardedHeaders.insecure"
      - "--providers.file.directory=/etc/traefik/"
      - "--providers.file.watch=true"
      - '--entryPoints.redis.address=:6379'
    ports:
      - target: 6379
        published: 31379
        mode: host
    environment:
      - AWS_ACCESS_KEY_ID=${ROUTE53_DNS_CHALLANGE_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ROUTE53_DNS_CHALLANGE_SECRET_KEY}
    deploy:
      replicas: ${OPS_TRAEFIK_REPLICAS}
      placement:
        constraints:
          - node.labels.traefik==true
    volumes:
      - /etc/traefik_certs:/etc/traefik_certs
    configs:
      - source: traefik_dynamic_config.yml
        target: /etc/traefik/dynamic_conf.yml
  whoami:
    dns: # Add this always for AWS, otherwise we get "No such image: " for docker services
      8.8.8.8

configs:
  traefik_dynamic_config.yml:
    file: ./traefik_dynamic_config.yml
