apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: restricted

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-privileged
  labels:
    pod-security.kubernetes.io/enforce: privileged
