{
 "title": "Docker Swarm Overview",
 "description": "Docker Swarm stacks and services metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Swarm Node",
    "query": {
     "query": "label_values(node_meta{job=~\"node-exporter\"}, node_name)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "auto" },
   {
    "name": "stack_namespace",
    "label": "Stack",
    "query": {
     "query": "query_result(count(container_last_seen{container_label_com_docker_stack_namespace=~\".+\"}) by (container_label_com_docker_stack_namespace))"
    }
   },
   {
    "name": "node_id",
    "query": {
     "query": "label_values(node_meta{instance=~\"$node_name\"}, node_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "osparc services only: docker service cpu core usage for node: {{$node_name}}",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (service_name) (label_replace(rate(container_cpu_usage_seconds_total{instance=~\"$node_name\",image=~\"^registry.*/simcore/services/.*\", id=~\"/docker/.*\"}[5m]), \"service_name\", \"$1\", \"image\", \"^registry.*/simcore/services/(.*)\") / on(instance) group_left() engine_daemon_engine_cpus_cpus{instance=~\"$node_name\"}) * 100",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "osparc simcore only: osparc simcore cpu core usage for node: {{$node_name}}",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (service_name) (label_replace(rate(container_cpu_usage_seconds_total{instance=~\"$node_name\",image=~\"^itisfoundation/.*\", id=~\"/docker/.*\"}[5m]), \"service_name\", \"$1\", \"image\", \"^itisfoundation/(.*)\") / on(instance) group_left() engine_daemon_engine_cpus_cpus{instance=~\"$node_name\"}) * 100",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(node_load1)" }
   ]
  },
  {
   "title": "Containers # (by service stack)",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 16, "w": 9, "x": 1, "y": 38 },
   "targets": [
    {
     "expr": "round(count(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval])) by (container_label_com_docker_stack_namespace))",
     "legendFormat": "{{container_label_com_docker_stack_namespace}}"
    }
   ]
  },
  {
   "title": "containers running per doker service task",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 38 },
   "targets": [
    {
     "expr": "round(sum(rate(container_last_seen{container_label_com_docker_stack_namespace=~\"$stack_namespace\",container_label_com_docker_swarm_node_id=~\"$node_id\"}[5m])) by (container_label_com_docker_swarm_service_name))",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[5m])) "
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_stack_namespace=~\"$stack_namespace\"}) by (container_label_com_docker_stack_namespace))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_service_name=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\", container_label_com_docker_stack_namespace=~\"$stack_namespace\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage by Container (top 10)",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[$__interval])) by (name)) * 100 ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage by Service",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[1m])) by (container_label_com_docker_swarm_service_name) * 100 ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage by Container (top 10)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg_over_time(container_memory_usage_bytes{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[$__interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage by Service",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Used {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "sum(container_memory_cache{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "Cached {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network and Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic on Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Cluster IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval]) )",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{container_label_com_docker_swarm_node_id=~\"$node_id\",container_label_com_docker_stack_namespace=~\"$stack_namespace\"}[$__interval])) ",
     "legendFormat": "Writes "
    }
   ]
  },
  {
   "title": "Network received by Service",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$__interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network transmitted by Service",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$__interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  }
 ]
}