{
 "title": "admin overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of registered users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(production_members_in_gid_1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of electrode-selector running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{image=~\"^.*/simcore/services/dynamic/electrode-selector.*$\",container_label_io_simcore_runtime_simcore_user_agent!=\"puppeteer\"}) OR clamp_max(absent(container_memory_usage_bytes{image=~\"^.*/simcore/services/dynamic/electrode-selector.*$\",container_label_io_simcore_runtime_simcore_user_agent!=\"puppeteer\"}),0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of sim4life-postpro running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{image=~\"^.*/simcore/services/dynamic/sim4life-postpro.*$\",container_label_io_simcore_runtime_simcore_user_agent!=\"puppeteer\"}) OR clamp_max(absent(container_memory_usage_bytes{image=~\"^.*/simcore/services/dynamic/sim4life-postpro.*$\",container_label_io_simcore_runtime_simcore_user_agent!=\"puppeteer\"}),0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of ti-postpro running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{image=~\"^.*/simcore/services/dynamic/ti-postpro.*$\",container_label_io_simcore_runtime_simcore_user_agent!=\"puppeteer\"}) OR clamp_max(absent(container_memory_usage_bytes{image=~\"^.*/simcore/services/dynamic/ti-postpro.*$\",container_label_io_simcore_runtime_simcore_user_agent!=\"puppeteer\"}),0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total CPU usage of all nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without (cpu, mode, instance, job) (rate(node_cpu_seconds_total{mode!=\"idle\"}[2m])) / count(count by (cpu) (node_cpu_seconds_total{})) OR clamp_max(absent(container_memory_usage_bytes{image=~\"^.*[.tip.itis.swiss].*/simcore/services/.*$\"}),0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Real-time RAM usage of all services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image=~\"^.*[.tip.itis.swiss].*/simcore/services/.*$\"}) OR clamp_max(absent(container_memory_usage_bytes{image=~\"^.*[.tip.itis.swiss].*/simcore/services/.*$\"}),0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}