version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2023-06-19T19-52-50Z
    init: true
    hostname: minio
    volumes:
      - minio_data:/data
    networks:
      - default
      - public
      - monitored
    ports:
      - target: 9000
    environment:
      - MINIO_ACCESS_KEY_FILE=minio_access_key
      - MINIO_SECRET_KEY_FILE=minio_secret_key
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - traefik.enable=true
        - traefik.docker.network=${PUBLIC_NETWORK}
        # direct access without path (necessary for minio client it does not like /path)
        - traefik.http.services.minio.loadbalancer.server.port=9000
        - traefik.http.services.minio.loadbalancer.healthcheck.path=/minio/health/ready
        - traefik.http.routers.minio.rule=Host(`${STORAGE_DOMAIN}`)
        - traefik.http.routers.minio.entrypoints=https
        - traefik.http.routers.minio.tls=true
        - traefik.http.routers.minio.middlewares=ops_gzip@swarm
    command: >
      server /data
    secrets:
      - minio_secret_key
      - minio_access_key
volumes:
  minio_data:


networks:
  public:
    external: true
    name: ${PUBLIC_NETWORK}
  monitored:
    name: ${MONITORED_NETWORK}
    external: true

secrets:
  minio_secret_key:
    external: true
  minio_access_key:
    external: true
