version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2024-10-29T16-01-48Z
    init: true
    hostname: minio
    volumes:
      - minio_data:/data
    networks:
      - default
      - public
      - monitored
    ports:
      - target: 9000
    environment:
      - MINIO_ACCESS_KEY_FILE=minio_access_key
      - MINIO_SECRET_KEY_FILE=minio_secret_key
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - traefik.enable=true
        - traefik.swarm.network=${PUBLIC_NETWORK}
        # direct access without path (necessary for minio client it does not like /path)
        - traefik.http.services.minio9000.loadbalancer.server.port=9000
        - traefik.http.services.minio9000.loadbalancer.healthcheck.path=/minio/health/ready
        - traefik.http.routers.minio9000.rule=Host(`${STORAGE_DOMAIN}`)
        - traefik.http.routers.minio9000.entrypoints=https
        - traefik.http.routers.minio9000.tls=true
        - traefik.http.routers.minio9000.service=minio9000
        #
        - traefik.http.services.minio9001.loadbalancer.server.port=9001
        - traefik.http.routers.minio9001.rule=Host(`${MONITORING_DOMAIN}`) && PathPrefix(`/minio`)
        - traefik.http.routers.minio9001.entrypoints=https
        - traefik.http.routers.minio9001.tls=true
        - traefik.http.routers.minio9001.service=minio9001
    command: >
      server /data --console-address ":9001"
    secrets:
      - minio_secret_key
      - minio_access_key
volumes:
  minio_data:


networks:
  public:
    external: true
    name: ${PUBLIC_NETWORK}
  monitored:
    name: ${MONITORED_NETWORK}
    external: true

secrets:
  minio_secret_key:
    external: true
  minio_access_key:
    external: true
