version: '3.8'

services:
    adminer:
        image: adminer:latest
        init: true
        ports:
        # PC -> Yuri: you should
        - 8080
        environment:
            ADMINER_DEFAULT_SERVER: db
            ADMINER_DESIGN: nette
        networks:
            - internal

    db:
        image: mariadb:10.11
        environment:
            - MYSQL_USER=${APPMOTION_GATEWAY_DB_USER}
            - MYSQL_PASSWORD=${APPMOTION_GATEWAY_DB_PASSWORD}
            - MYSQL_DATABASE=${APPMOTION_GATEWAY_DB_DATABASE}
            - MYSQL_RANDOM_ROOT_PASSWORD=1
        volumes:
            - db_volume:/var/lib/mysql
        networks:
            - internal

    api:
        # PC -> Yuri: should we pass this image name via a env var?
        image: itisfoundation/appmotion-gateway-php-apache-8.2:latest
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
        configs:
          - source: api_env_config
            target: /app/.env
        networks:
            - internal
            - simcore_default
        deploy: {}
          
configs:
    # SEE https://docs.docker.com/compose/compose-file/05-services/#configs
    api_env_config:
        external: true

volumes:
    # SEE https://docs.docker.com/compose/compose-file/07-volumes/
    # PC -> Yuri: this volume needs to be backuped
    db_volume:

networks:
    # SEE https://docs.docker.com/compose/compose-file/06-networks/
    internal:
        external: false
    simcore_default:
        # PC -> Yuri: this network should allow talking internally with the payments service (can be the default or a new one)
        external: true
