version: '3.7'
services:
  filestash:
    dns: # Add this always for AWS, otherwise we get "No such image: " for docker services
      8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.filestash==true
