{
 "title": "Smoke Ping",
 "description": "Smoke Ping using https://github.com/SuperQ/smokeping_prober\r\nwith \r\nlatency heatmap\r\nlatency graph\r\npacket loss gragh\r\n",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "target",
    "query": "label_values(smokeping_response_duration_seconds_bucket, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Smoke Ping - $target",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(smokeping_response_duration_seconds_bucket{host=\"$target\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Packet Loss - $target",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Loss %" }
   ],
   "targets": [
    {
     "expr": "(smokeping_requests_total{host=\"$target\"} - smokeping_response_duration_seconds_count{host=\"$target\"})/smokeping_requests_total{host=\"$target\"} ",
     "legendFormat": "Percentage"
    },
    {
     "expr": "(smokeping_requests_total{host=\"$target\"} - smokeping_response_duration_seconds_count{host=\"$target\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Latency - $target",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "smokeping_response_duration_seconds_sum{host=\"$target\"} / smokeping_response_duration_seconds_count{host=\"$target\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}