{
 "title": "Traefik2",
 "description": "Dashboard for Traefik2/Prometheus, based upon the one by ichasco. Updated for Traefik2 metric names.",
 "tags": [
  "traefik",
  "load-balancer",
  "docker",
  "prometheus",
  "link"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job:", "query": "traefik_ops, traefik_simcore" },
   {
    "name": "protocol",
    "label": "Service:",
    "query": {
     "query": "label_values(traefik_service_requests_total, protocol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "404 Error Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"404\",job=\"$job\",method=\"GET\",protocol=~\"$protocol\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{job=\"$job\"}) / sum(traefik_entrypoint_requests_total{job=\"$job\"}) * 1000"
    }
   ]
  },
  {
   "title": "Bad Status Code Count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{code=\"404\",method=\"GET\",job=\"$job\",protocol=~\"$protocol\"}[$__interval])) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{protocol=~\"$protocol\"}) / sum(traefik_entrypoint_requests_total{protocol=~\"$protocol\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{job=\"$job\"}[$__interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Access to backends",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{protocol=~\"http|https\",code=\"200\",job=\"$job\"}[$__interval])) by (service)",
     "legendFormat": "{{service}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "ENTRYPOINT - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "BACKEND - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Status Code Count per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{protocol=~\"$protocol\",job=\"$job\"}[$__interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}