version: "3.7"
services:
  mongodb:
    deploy:
      placement:
        constraints: []

  elasticsearch:
    deploy:
      placement:
        constraints: []

  graylog:
    deploy:
      placement:
        constraints: []
