#!/bin/sh

set -x

if [ ${UPDATE_CERTIFICATES} ]; then
    cp /secrets/domain.crt /usr/local/share/ca-certificates
    cp /secrets/rootca.crt /usr/local/share/ca-certificates
    update-ca-certificates
fi
registry serve /etc/docker/registry/config.yml
