# Minio config
scrape_configs:
  # to generate the token use the following
  # docker run -v /etc/ssl/certs:/etc/ssl/certs:ro --network host \
  #   -e MC_HOST_local="https://12345678:12345678@osparc.local:10000" \
  #   minio/mc admin prometheus generate local
  # SIMCORE -------------------------------------------------------------------
  - job_name: "simcore"
    scrape_interval: 73s
    relabel_configs:
      - source_labels: [__meta_dns_name]
        separator: ;
        regex: ^(.*\.)?(.*?)[_-].*$
        target_label: deployment
        replacement: $2
        action: replace
      - source_labels: [__meta_dns_name]
        separator: ;
        regex: ^.*?[_-](.*)$
        target_label: service_name
        replacement: $1
        action: replace
    # Handle with "tasks." when there are multiple replica accrding to https://www.innoq.com/en/blog/scraping-docker-swarm-service-instances-with-prometheus/
    dns_sd_configs:
      - names:
          - "tasks.master_webserver"
        type: "A"
        port: 8080
      - names:
          - "tasks.master_storage"
        type: "A"
        port: 8080
      - names:
          - "tasks.master_director"
        type: "A"
        port: 8080
      - names:
          - "tasks.master_rabbit"
        type: "A"
        port: 15692
      - names:
          - "tasks.master_traefik"
        type: "A"
        port: 8082
      - names:
          - "tasks.master_redis-exporter"
        type: "A"
        port: 9121
      - names:
          - "tasks.master_postgres-exporter"
        type: "A"
        port: 9187
      - names:
          - "tasks.dcgm-exporter"
        type: "A"
        port: 9400
      - names:
          - "tasks.pgsql-query-exporter"
        type: "A"
        port: 9560
