{{- range .Values.certificates -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .certName }}
spec:
  # https://github.com/emberstack/kubernetes-reflector?tab=readme-ov-file#cert-manager-support
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "traefik"
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  secretName: {{ .secretName }}
  dnsNames:
{{- range .dnsNames }}
    - "{{ . }}"
{{- end }}
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
---
{{- end -}}
