{
 "title": "s4l admin overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serviceuuid",
    "label": "Deepdive: Service UUID",
    "query": {
     "query": "label_values(s4l_user_feature_time,node_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "plattform overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of s4l running (excluding automated testing)",
   "type": "timeseries",
   "gridPos": { "h": 28, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "osparc_container_instances_s4lcore",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of registered s4l users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(osparc_production_members_in_gid_4)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of s4l buffer machines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "osparc_autoscaling_machines_buffer",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active (\"hot\") s4l machines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "osparc_autoscaling_machines_active",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of total (buffer+active) s4l machines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "osparc_autoscaling_machines_active + osparc_autoscaling_machines_buffer",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "s4l-deepdive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Time spent in ...",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, job, monitor, node_id) (s4l_user_feature_time{node_id=\"$serviceuuid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clicked on ...",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, job, monitor, node_id) (s4l_user_feature_count{node_id=\"$serviceuuid\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}