version: "3.8"
services:
  auto-deployment-agent:
    image: local/deployment-agent:development
    volumes:
      - ../../../osparc-deployment-agent:/devel/services/deployment-agent
    environment:
      - SC_BOOT_MODE=debug-ptvsd
    ports:
      - "3005:3000"
