apiVersion: v2
name: tracing-stack
description: A wrapper chart for tracing-stack-single and open telemetry collector

type: application

version: 0.0.1

appVersion: 0.0.1

dependencies:
  - name: victoria-traces-single
    version: 0.1.11
    repository: "https://victoriametrics.github.io/helm-charts/"
  - name: opentelemetry-collector
    version: 0.162.0
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
