{
 "title": "Ceph  - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "cluster",
    "query": {
     "query": "label_values(ceph_cluster_total_bytes,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_health_status{job=\"$job\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w_in_bytes{job=\"$job\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_r_out_bytes{job=\"$job\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_cluster_total_bytes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) ((ceph_cluster_total_bytes{job=\"$job\"}-ceph_cluster_total_used_bytes{job=\"$job\"})/ceph_cluster_total_bytes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, pool_id) (ceph_pool_objects{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_op_w_in_bytes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_op_r_out_bytes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cluster='$cluster',alertstate='firing',alertname=~'^CephCluster.*'}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_w{job=\"$job\"}[5m]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_r{job=\"$job\"}[5m]))"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_cluster_total_used_bytes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_mon_num_sessions{cluster='$cluster'})"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (instance, ceph_daemon) (ceph_mon_quorum_status{job=\"$job\"})"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (instance, ceph_daemon) (ceph_osd_up{job=\"$job\"}) - count without (instance, ceph_daemon) (ceph_osd_in{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\"} == 0.0) OR vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_up{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_in{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_numpg{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Avg Op Write Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{job=\"$job\"}[5m]) / rate(ceph_osd_op_w_latency_count{job=\"$job\"}[5m]) >= 0)"
    }
   ]
  },
  {
   "title": "Avg  Op Read Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_r_latency_sum{job=\"$job\"}[5m])/rate(ceph_osd_op_r_latency_count{job=\"$job\"}[5m]) >= 0)"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_cluster_total_bytes{job=\"$job\"})",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "sum without (instance) (ceph_cluster_total_bytes{job=\"$job\"}-ceph_cluster_total_used_bytes{job=\"$job\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum without (instance) (ceph_cluster_total_used_bytes{job=\"$job\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w{job=\"$job\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_r{job=\"$job\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w_in_bytes{job=\"$job\"}[1m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_r_out_bytes{job=\"$job\"}[1m]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Recovered Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(ceph_osd_recovery_bytes[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pool Bytes Recovered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum((ceph_pool_num_bytes_recovered{job='$job'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{job='$job'})) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) ((ceph_pool_objects{job='$job'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{job='$job'}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) ((ceph_pool_quota_bytes{job='$job'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{job='$job'}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Recovered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pool_id) ((ceph_pool_num_objects_recovered{job='$job'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{job='$job'}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Objects in the Cluster",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pool_id) (ceph_pool_objects{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "PGs State",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_active{job=\"$job\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_clean{job=\"$job\"})",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_peering{job=\"$job\"})",
     "legendFormat": "Peering"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_degraded{job=\"$job\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_stale{job=\"$job\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_unclean_pgs{job=\"$job\"})",
     "legendFormat": "Unclean"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_undersized{job=\"$job\"})",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_incomplete{job=\"$job\"})",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_forced_backfill{job=\"$job\"})",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_inconsistent{job=\"$job\"})",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_forced_recovery{job=\"$job\"})",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_creating{job=\"$job\"})",
     "legendFormat": "Creating"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_wait_backfill{job=\"$job\"})",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_deep{job=\"$job\"})",
     "legendFormat": "Deep"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_scrubbing{job=\"$job\"})",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_recovering{job=\"$job\"})",
     "legendFormat": "Recovering"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_repair{job=\"$job\"})",
     "legendFormat": "Repair"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_down{job=\"$job\"})",
     "legendFormat": "Down"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_peered{job=\"$job\"})",
     "legendFormat": "Peered"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_backfill{job=\"$job\"})",
     "legendFormat": "Backfill"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_remapped{job=\"$job\"})",
     "legendFormat": "Remapped"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_backfill_toofull{job=\"$job\"})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_degraded{job=\"$job\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_stale{job=\"$job\"})",
     "legendFormat": "Stale"
    },
    {
     "expr": "sum without (instance, pool_id) (ceph_pg_undersized{job=\"$job\"})",
     "legendFormat": "Undersized"
    }
   ]
  },
  {
   "title": "Recovery Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_recovery_ops{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "OPS"
    }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{job='$job'}"
    }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "ceph_osd_commit_latency_ms{job='$job'}"
    }
   ]
  },
  {
   "title": "OSD Read Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_r_latency_sum{job=\"$job\"}[5m]) / rate(ceph_osd_op_r_latency_count{job=\"$job\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "OSD Write Op Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_w_latency_sum{job=\"$job\"}[5m]) / rate(ceph_osd_op_w_latency_count{job=\"$job\"}[5m]) >= 0"
    }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg without (instance,ceph_daemon) (rate(ceph_osd_op_r_latency_sum{job=\"$job\"}[5m]) / rate(ceph_osd_op_r_latency_count{job=\"$job\"}[5m]) >= 0)",
     "legendFormat": "read"
    },
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{job=\"$job\"}[5m]) / rate(ceph_osd_op_w_latency_count{job=\"$job\"}[5m]) >= 0)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{job=\"$job\"})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_commit_latency_ms{job=\"$job\"})",
     "legendFormat": "commit"
    }
   ]
  },
  { "title": "Node Statistics (NodeExporter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum without (instance) (node_memory_Active_anon_bytes{job='$job'})",
     "legendFormat": "Cluster Memory Usage"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job='$job',mode!=\"idle\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_read_bytes_total{job='$job'}[2m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_written_bytes_total{job='$job'}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Space in root filesystem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{job=\"$job\", mountpoint='/', device != 'rootfs'})*100 / (node_filesystem_size_bytes{job=\"$job\", mountpoint='/', device != 'rootfs'})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}