{
 "title": "Metrics",
 "description": "Simcore metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "deployment", "label": "Deployment", "query": "production, staging" },
   { "name": "Postgresql", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Simcore usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of registered Users by type [current]",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  role AS metric,\n  sum(count(id)) OVER (PARTITION BY role ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n  role = 'USER'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  role AS metric,\n  sum(count(id)) OVER (PARTITION BY role ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n  role = 'TESTER'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  role AS metric,\n  sum(count(id)) OVER (PARTITION BY role ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n  role = 'GUEST'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Login rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint)  (rate(http_requests_total{endpoint=~\"/v0/me\", http_status=~\"2[0-9]+\", app_name=~\".+webserver\", deployment=\"$deployment\"}[$__range]))*$__range_ms/1000",
     "legendFormat": "endpoint: {{endpoint}}"
    }
   ]
  },
  {
   "title": "Current connections - Redis [current]",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(redis_key_value{key=~\".+:alive\", deployment=\"$deployment\"})",
     "legendFormat": "Connected clients"
    },
    {
     "expr": "sum(redis_key_size{deployment=\"$deployment\"}) by ()",
     "legendFormat": "Resources per client"
    }
   ]
  },
  {
   "title": "New users per second [time]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  (CASE WHEN sum(id) >= lag(sum(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) THEN sum(id) - lag(sum(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) WHEN lag(sum(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) IS NULL THEN NULL ELSE sum(id) END)/extract(epoch from min(created_at) - lag(min(created_at)) OVER (ORDER BY $__timeGroup(created_at,$__interval))) AS \"id\"\nFROM users\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total number of anonymous users who are redirected to oSPARC from the SPARC Portal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  sum(count(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n  $__timeFilter(created_at) AND\n  role = 'GUEST' AND\n  created_ip NOT LIKE '195.176.8.%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total number of anonymous users who are redirected to oSPARC from Z43",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  sum(count(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n  $__timeFilter(created_at) AND\n  role = 'GUEST' AND\n  created_ip LIKE '195.176.8.%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hits per published study [current]",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (http_requests_total{endpoint=~\"/study/.+\", app_name=~\".*webserver\", deployment=\"$deployment\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Number of services running by version [time]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name) (label_replace(container_tasks_state:count_by_image, \"service_name\", \"$3\", \"image\", \".*/simcore/services/(dynamic|comp)/([a-zA-Z0-9]*/)?(.*)\"))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Service started [time]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(simcore_simcore_service_webserver_services_started_total:sum_by_service_key_service_tag{deployment=\"$deployment\"}[$__range])*$__range_ms/1000",
     "legendFormat": "{{service_key}}:{{service_tag}}"
    },
    {
     "expr": "rate(simcore_simcore_service_director_services_started_total:sum_by_service_key_service_tag{deployment=\"$deployment\"}[$__range])*$__range_ms/1000",
     "legendFormat": "{{service_key}}:{{service_tag}}"
    }
   ]
  },
  { "title": "Cluster usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total CPU consumption  [cpu-hours]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_cpu_seconds_total{mode!=\"idle\"}[$__range]))/60/60",
     "legendFormat": "increase of cpu hours over time range"
    }
   ]
  },
  {
   "title": "Overall data storage [GB]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_avail_bytes{mountpoint=\"/\"})",
     "legendFormat": "data usage"
    },
    {
     "expr": "-sum(delta(node_filesystem_avail_bytes{mountpoint=\"/\"}[$__range]))",
     "legendFormat": "variation"
    }
   ]
  },
  {
   "title": "CPU consumption per node [time]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[$__range]) * on(instance) group_left(node_name) node_meta{}) by (node_name)  * 100)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Used disk space  [current]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_avail_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\"} * on(instance) group_left(node_name) node_meta{}) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Available disk space [current]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{mountpoint=\"/\"} /1024/1024/1024 * on(instance) group_left(node_name) node_meta{}) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}