# Internal VARIABLES ------------------------------------------------
REPO_BASE_DIR := $(shell git rev-parse --show-toplevel)

# TARGETS --------------------------------------------------
include ${REPO_BASE_DIR}/scripts/common.Makefile
include ${REPO_BASE_DIR}/charts/common-k8s.Makefile
include $(REPO_CONFIG_LOCATION)
