services:
  pg_backup:
    image: eeshugerman/postgres-backup-s3:14
    environment:
      SCHEDULE: '@midnight'
      BACKUP_KEEP_DAYS: 30
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${POSTGRES_S3_BACKUP_BUCKET}
      S3_PREFIX: ${POSTGRES_S3_BACKUP_S3_PREFIX}
      S3_ENDPOINT: ${S3_ENDPOINT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
    - public  # in order to connect to postgres
    deploy:
      placement:
        constraints:
          - node.labels.ops == true
      resources:
        limits:
          memory: 512M
          cpus: "1"
        reservations:
          memory: 64M
          cpus: "0.1"

networks:
  public:
    name: ${PUBLIC_NETWORK}
    external: true
