version: '3.7'
services:
  dbbackup:
    image: justb4/pgbackup:10
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /tank:/backup
    environment:
    - PGB_SCHEDULE=0 * * * * # Every hours
    networks:
    - monitored
    deploy:
      placement:
        constraints:
          - node.labels.pgbackup==true
networks:
  monitored:
    name: ${MONITORED_NETWORK}
    external: true
