{
 "title": "Aiohttp services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "storage, webserver" },
   { "name": "deployment", "label": "Deployment", "query": "master, staging, production" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"${deployment}-simcore_${deployment}_${service}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"${deployment}-simcore_${deployment}_${service}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requests in progress",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(method, endpoint) (http_in_flight_requests{app_name=\"simcore_service_${service}\", deployment=\"${deployment}\"})",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Avg request duration (over last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method, endpoint) (increase(http_request_latency_seconds_sum{app_name=\"simcore_service_${service}\", deployment=\"${deployment}\"}[5m])) / sum by(method, endpoint) (increase(http_request_latency_seconds_count{app_name=\"simcore_service_${service}\", deployment=\"${deployment}\"}[5m]))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests count (last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(method, endpoint) (round(increase(http_requests_total{job=\"simcore\", app_name=\"simcore_service_${service}\", deployment=\"${deployment}\"}[5m]), 1))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Http status count (last 5min)",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status) (round(increase(http_requests_total{app_name=\"simcore_service_${service}\", deployment=\"$deployment\"}[5m]), 1))",
     "legendFormat": "{{http_status}}"
    }
   ]
  }
 ]
}