{
 "title": "API server",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Request latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_highr_seconds_bucket{job=\"simcore\", service_name=\"api-server\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"master-simcore_master_api-server\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"master-simcore_master_api-server\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg request duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{service_name=\"api-server\"}[5m]) / rate(http_request_duration_seconds_count{service_name=\"api-server\"}[5m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Avg request size",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum{service_name=\"api-server\"} [5m]) / rate(http_request_size_bytes_count{service_name=\"api-server\"} [5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Avg response size",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_sum{service_name=\"api-server\"}[5m]) / rate(http_response_size_bytes_count{service_name=\"api-server\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests count (last 15min)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "delta(http_requests_total{job=\"simcore\", service_name=\"api-server\"}[15m]) > 0",
     "legendFormat": "{{method}} {{handler}} (status={{status}})"
    }
   ]
  }
 ]
}