{
 "title": "Metrics",
 "description": "Simcore metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Swarm node", "query": { "query": "node_meta" } },
   { "name": "deployment", "query": "master" }
  ]
 },
 "panels": [
  { "title": "Simcore usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of registered Users in DB [current]",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n role AS metric,\n sum(count(id)) OVER (PARTITION BY role ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n role = 'USER'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n role AS metric,\n sum(count(id)) OVER (PARTITION BY role ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n role = 'TESTER'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n role AS metric,\n sum(count(id)) OVER (PARTITION BY role ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n role = 'GUEST'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Current connections - Redis [current]",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(redis_key_value{key=~\".+:alive\"})",
     "legendFormat": "Connected clients"
    },
    {
     "expr": "count(redis_key_size{key=~\".+:resources\"})",
     "legendFormat": "Resources used"
    }
   ]
  },
  {
   "title": "New users per second [time]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n $__timeGroupAlias(created_at,$__interval),\n (CASE WHEN sum(id) >= lag(sum(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) THEN sum(id) - lag(sum(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) WHEN lag(sum(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) IS NULL THEN NULL ELSE sum(id) END)/extract(epoch from min(created_at) - lag(min(created_at)) OVER (ORDER BY $__timeGroup(created_at,$__interval))) AS \"id\"\nFROM users\nWHERE\n $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of services running by version [time]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name) (label_replace(container_tasks_state:count_by_image, \"service_name\", \"$3\", \"image\", \".*/simcore/services/(dynamic|comp)/([a-zA-Z0-9]*/)?(.*)\"))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Service started [time]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate({__name__=~\"simcore_simcore_service_(director|webserver)_services_started_total:sum_by_service_key_service_tag\"}[$__range])*$__range_ms/1000, \"service_name\", \"$3\", \"service_key\", \"simcore/services/(dynamic|comp)/([a-zA-Z0-9]*/)?(.*)\")",
     "legendFormat": "{{service_name}}:{{service_tag}}"
    }
   ]
  },
  {
   "title": "CPU usage by Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\", container_label_com_docker_swarm_service_name=~\".*simcore.*\"}[1m]), \"service_name\", \"$1\", \"container_label_com_docker_swarm_service_name\", \".*_(.*)\")) by (service_name) * 100",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Service started / day [time]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(increase({__name__=~\"simcore_simcore_service_(director|webserver)_services_started_total:sum_by_service_key_service_tag\"}[24h]), \"service_name\", \"$3\", \"service_key\", \"simcore/services/(dynamic|comp)/([a-zA-Z0-9]*/)?(.*)\")",
     "legendFormat": "{{service_name}}:{{service_tag}}"
    }
   ]
  },
  { "title": "Cluster usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU consumption per node [time]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[$__range]) * on(instance) group_left(node_name) node_meta{}) by (instance) * 100)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Used disk space [current]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(1 - sum(node_filesystem_avail_bytes{mountpoint=~\"/\", device!~'rootfs'}/node_filesystem_size_bytes{mountpoint=~\"/\", device!~'rootfs'} * on(instance) group_left(node_name) node_meta{}) by (instance))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Currently opened files decriptor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(process_open_fds)" }
   ]
  }
 ]
}