{
 "title": "Fastapi services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "simcore service",
    "query": "agent, api-server, autoscaling, catalog, clusters-keeper, datcore-adapter, director-v2, dynamic-schdlr, invitations, payments, resource-usage-tracker"
   },
   { "name": "deployment", "label": "deployment", "query": "staging, production, master" }
  ]
 },
 "panels": [
  {
   "title": "Request duration heatmap",
   "type": "heatmap",
   "description": "Each temporal slice can be thought of as a histogram of request durations",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (increase(http_request_duration_highr_seconds_bucket{job=\"simcore\", service_name=\"$service\", deployment=\"$deployment\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"${deployment}-simcore_${deployment}_${service}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"${deployment}-simcore_${deployment}_${service}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requests in progress",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "http_requests_inprogress{service_name=\"$service\", deployment=\"$deployment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg request duration (over last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler, method) (increase(http_request_duration_seconds_sum{service_name=\"$service\", deployment=\"$deployment\"}[5m])) / sum by(handler, method) (increase(http_request_duration_seconds_count{service_name=\"$service\", deployment=\"$deployment\"}[5m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Avg request size (last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(handler) (increase(http_request_size_bytes_sum{service_name=\"$service\", deployment=\"$deployment\"}[5m])) / sum by(handler) (increase(http_request_size_bytes_count{service_name=\"$service\", deployment=\"$deployment\"}[5m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Avg response size (last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(handler) (increase(http_response_size_bytes_sum{service_name=\"$service\", deployment=\"$deployment\"}[5m])) / sum by(handler) (increase(http_response_size_bytes_count{service_name=\"$service\", deployment=\"$deployment\"}[5m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests count (last 5min)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_requests_total{job=\"simcore\", service_name=\"$service\", deployment=\"$deployment\"}[5m]))",
     "legendFormat": "status={{status}}"
    }
   ]
  },
  {
   "title": "Average request duration (since t=-infinity)",
   "type": "stat",
   "gridPos": { "h": 30, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, handler) (http_request_duration_seconds_sum{service_name=\"$service\", deployment=\"$deployment\"}) / sum by(method, handler) (http_request_duration_seconds_count{service_name=\"$service\", deployment=\"$deployment\"})",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "95% quantile (since t=-infinity)",
   "type": "stat",
   "gridPos": { "h": 30, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, handler) (http_request_duration_seconds_bucket{service_name=\"$service\", deployment=\"$deployment\"}))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  }
 ]
}