{
 "title": "Simcore services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "simcore service",
    "query": "agent, api-server, autoscaling, catalog, clusters-keeper, datcore-adapter, director-v2, dynamic-scheduler, invitations, payments, resource-usage-tracker"
   }
  ]
 },
 "panels": [
  {
   "title": "Request duration heatmap",
   "type": "heatmap",
   "description": "Each temporal slice can be thought of as a histogram of request durations",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_highr_seconds_bucket{job=\"simcore\", service_name=\"$service\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"master-simcore_master_$service\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"master-simcore_master_$service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requests in progress",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "http_requests_inprogress{service_name=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg request duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{service_name=\"$service\"}[10m]) / rate(http_request_duration_seconds_count{service_name=\"$service\"}[10m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Avg request size",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_sum{service_name=\"$service\"} [5m]) / rate(http_request_size_bytes_count{service_name=\"$service\"} [5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Avg response size",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_sum{service_name=\"$service\"}[5m]) / rate(http_response_size_bytes_count{service_name=\"$service\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests count (last 15min)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by (method, handler, status) (delta(http_requests_total{job=\"simcore\", service_name=\"$service\"}[15m]) > 0)",
     "legendFormat": "{{method}} {{handler}} (status={{status}})"
    }
   ]
  }
 ]
}