# chart templates don't account for http.pathPrefix in metrics endpoints
# Pod Monitor fix not released yet: https://github.com/VictoriaMetrics/helm-charts/pull/3073
# VMServiceScrape: no fix available at all

{{- $single := index .Values "victoria-traces-single" }}
{{- $pathPrefix := index $single.server.extraArgs "http.pathPrefix" }}
{{- $serverLabels := $single.server.podLabels }}

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: victoria-traces-single
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.simcore.io/name: {{ index $serverLabels "app.simcore.io/name" }}
      app.simcore.io/part-of: {{ index $serverLabels "app.simcore.io/part-of" }}
  endpoints:
    - port: http
      path: {{ $pathPrefix }}/metrics
      # alerts vthealth/victorialogs configured in `victoria-metrics-k8s-stack`
      # rely on job=~".*victoriatraces.*". To make them work, we need to adjust
      # the job label
      relabelConfigs:
        - targetLabel: job
          replacement: victoriatraces
