apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: adminer-network-policy
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
spec:
  selector: app.kubernetes.io/instance == "{{ .Release.Name }}"
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ .Values.service.port }}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - 5432
    # allow dns requests to public dns servers
    - action: Allow
      protocol: UDP
      destination:
        ports:
          - 53
