# https://github.com/grafana-community/helm-charts/blob/grafana-12.4.4/charts/grafana/README.md#sidecar-for-datasources
{{- $vmauth := index .Values "vm-k8s-stack" "vmauth" }}
{{- $svcName := printf "vmauth-%s" (index .Values "vm-k8s-stack" "fullnameOverride") }}
{{- $port := $vmauth.spec.port }}
{{- $pathPrefix := index $vmauth.spec.extraArgs "http.pathPrefix" }}
{{- $clusterDomain := index .Values "vm-k8s-stack" "global" "cluster" "dnsDomain" }}
{{- $url := printf "http://%s.%s.svc.%s:%s%s/select/prometheus/" $svcName .Release.Namespace $clusterDomain $port $pathPrefix }}
{{- $uid := .Values.metricsDatasourceUid }}
{{- $type := .Values.metricsDatasourceType }}

{{- define "vmk8s.datasource" -}}
type: {{ .type }}
access: proxy
url: {{ .url }}
# if edited in grafana, the datasource will be out-of-sync (helm won't notice the change)
editable: false
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: victoria-metrics-grafana-datasource
  labels:
    # special label to be picked up by the grafana sidecar
    grafana_datasource: true_string
    # TODO: add reusable common labels
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 }}
    app.kubernetes.io/instance: {{ .Release.Name | trunc 63 }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
stringData:
  datasource.yaml: |-
    apiVersion: 1
    # remove the pre-split single datasource so its uid can be reused by "All".
    # https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
    deleteDatasources:
      - name: VictoriaMetrics
        orgId: 1
    datasources:
      - name: VictoriaMetrics All
        uid: {{ $uid }}
        {{- include "vmk8s.datasource" (dict "type" $type "url" $url) | nindent 8 }}
        # historically, this is 1st datasource in grafana. Grafana sets
        # first datasource automatically to be default. So, isDefault setting
        # is not respected in this case
        isDefault: true
      - name: VictoriaMetrics Kubernetes only
        uid: {{ $uid }}-kubernetes
        {{- include "vmk8s.datasource" (dict "type" $type "url" $url) | nindent 8 }}
        jsonData:
          # https://docs.victoriametrics.com/victoriametrics/#prometheus-querying-api-enhancements
          customQueryParameters: "extra_label=cluster=kubernetes"
      - name: VictoriaMetrics Docker Swarm only
        uid: {{ $uid }}-swarm
        {{- include "vmk8s.datasource" (dict "type" $type "url" $url) | nindent 8 }}
        jsonData:
          customQueryParameters: "extra_label=cluster=docker_swarm"
