{{- $vmauth := index .Values "vm-k8s-stack" "vmauth" }}
{{- $fullname := index .Values "vm-k8s-stack" "fullnameOverride" }}
{{- $svcName := printf "vmauth-%s" $fullname }}
{{- $port := $vmauth.spec.port }}
{{- $pathPrefix := index $vmauth.spec.extraArgs "http.pathPrefix" }}
{{- $clusterDomain := index .Values "vm-k8s-stack" "global" "cluster" "dnsDomain" }}
# https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-datasources
apiVersion: v1
kind: Secret
metadata:
  name: victoria-metrics-grafana-datasource
  labels:
    # special label to be picked up by the grafana sidecar
    grafana_datasource: true_string
    # TODO: add reusable common labels
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 }}
    app.kubernetes.io/instance: {{ .Release.Name | trunc 63 }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: {{ .Values.grafanaMetricsDatasourceType }}
        uid: {{ .Values.grafanaMetricsDatasourceUid }}
        access: proxy
        url: http://{{ $svcName }}.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:{{ $port }}{{ $pathPrefix }}/select/0/prometheus/
        # not default on purpose: dashboards must reference the uid explicitly
        isDefault: false
        editable: false
