version: "3.7"
volumes:
  batmanpanel_data: {}
configs:
  batmanpanel_nginx_config:
    file: ./nginx.conf
  batmanpanel_nginx_default_config:
    file: ./default.conf
services:
  batman_nginx:
    image: flashspys/nginx-static
    networks:
      - public
    configs:
      - source: batmanpanel_nginx_config
        target: /etc/nginx/nginx.conf
      - source: batmanpanel_nginx_default_config
        target: /etc/nginx/conf.d/default.conf
    deploy:
      placement:
        constraints:
          - node.labels.leader==true
      labels:
        - traefik.enable=true
        - traefik.docker.network=${PUBLIC_NETWORK}
        - traefik.http.services.batman_nginx.loadbalancer.server.port=80
        - traefik.http.routers.batman_nginx.rule=Host(`${BATMANPANELS_DOMAIN}`)
        - traefik.http.routers.batman_nginx.entrypoints=https
        - traefik.http.routers.batman_nginx.priority=1
        - traefik.http.routers.batman_nginx.tls=true
        - traefik.http.routers.batman_nginx.middlewares=ops_whitelist_ips@docker
      resources:
        limits:
          memory: 64M
    volumes:
      - batmanpanel_data:/static:r
  batman_tablegeneration:
    image: python:3.10
    networks:
      - public
    command: ["/bin/bash", "-c", "pip install -r /batmanpanels/requirements.txt && cd /batmanpanels && python3 main.py"]
    deploy:
      placement:
        constraints:
          - node.labels.leader==true
      resources:
        limits:
          memory: 256M
    volumes:
      - batmanpanel_data:/content:rw
      - ./:/batmanpanels/:r
networks:
  public:
    external: true
    name: ${PUBLIC_NETWORK}
