name: CI

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Show python version
        run: python --version

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
