name: CI

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Define python
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: "${{ env.PYTHON_VERSION }}"

      - name: Show python version
        run: python --version

      - name: Install dependencies
        run: |
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit
        run: pre-commit run --all-files
