name: CI

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5  # defaults to .python-version

      - name: Show python version
        run: python --version

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  trivy-scan-charts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load ci.env into job environment
        run: cat charts/ci.env >> "$GITHUB_ENV"

      - name: Render charts
        uses: helmfile/helmfile-action@v2.4.3
        with:
          helmfile-version: v0.165.0
          helmfile-workdirectory: charts/
          helmfile-args: >-
            -f helmfile.ci.yaml
            template
            --output-dir /tmp/rendered
            --output-dir-template={{.OutputDir}}

      - name: Install trivy # https://github.com/aquasecurity/setup-trivy
        uses: aquasecurity/setup-trivy@v0.2.6

      - name: Trivy config scan
        run: >-
          trivy config
            --severity CRITICAL,HIGH,MEDIUM
            --exit-code 1
            --ignorefile charts/.trivyignore.yaml
            /tmp/rendered
