name: Code static analysis

on:
  push:
    branches:
      - "main"
  pull_request:
  merge_group: # necessary when adding a PR to a merge queue
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6  # defaults to .python-version

      - name: Show python version
        run: python --version

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  trivy-scan-charts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure config location
        run: echo $(realpath charts/.ci-deployment/repo.config) > .config.location

      - name: Install helmfile
        uses: helmfile/helmfile-action@v2.4.4
        with:
          helmfile-version: v0.165.0 # keep in sync with charts/Makefile and version in running clusters
          helmfile-auto-init: 'true'
          helmfile-args: --version

      - name: Install trivy # https://github.com/aquasecurity/setup-trivy
        uses: aquasecurity/setup-trivy@v0.2.6

      - name: Run trivy scan
        run: make -C charts trivy-scan
