name: Code static analysis

on:
  push:
    branches:
      - "main"
  pull_request:
  merge_group: # necessary when adding a PR to a merge queue
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6  # defaults to .python-version

      - name: Show python version
        run: python --version

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  helmfile-static-checks:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup helmfile
        uses: ./.github/actions/setup-helmfile

      - name: Lint helmfile
        run: make --directory ./charts helmfile-lint

      - name: Render helmfile templates
        run: make --directory ./charts helmfile-template

  trivy-scan-charts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup helmfile
        uses: ./.github/actions/setup-helmfile

      - name: Install trivy # https://github.com/aquasecurity/setup-trivy
        uses: aquasecurity/setup-trivy@3fb12ec12f41e471780db15c232d5dd185dcb514 # v0.2.6
        with:
          # tracked by renovate via github actions
          # see list of supported `with version` actions
          # https://docs.renovatebot.com/modules/manager/github-actions/#withversion-support-for-built-in-actions
          # NOTE: keep in sync with trivy version in makefile
          version: v0.71.2

      - name: Run trivy scan
        run: make --directory ./charts trivy-scan
