name: Code static analysis

on:
  push:
    branches:
      - "main"
  pull_request:
  merge_group: # necessary when adding a PR to a merge queue
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6  # defaults to .python-version

      - name: Show python version
        run: python --version

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  helmfile-static-checks:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup helmfile
        uses: ./.github/actions/setup-helmfile

      - name: Lint helmfile
        run: make -C charts helmfile-lint

      - name: Render helmfile templates
        run: make -C charts helmfile-template

  trivy-scan-charts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup helmfile
        uses: ./.github/actions/setup-helmfile

      - name: Install trivy # https://github.com/aquasecurity/setup-trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          # tracked by renovate
          version: v0.71.2

      - name: Run trivy scan
        run: make -C charts trivy-scan
