name: precommit

# Adapted from https://thomasthornton.cloud/2022/08/04/running-pre-commit-hooks-as-github-actions/
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hmcts/cnp-azuredevops-libraries
          path: cnp-azuredevops-libraries

      - uses: actions/setup-python@v4

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.30.8

      - uses: pre-commit/action@v3.0.0
