{{- $stack := index .Values "vm-k8s-stack" -}}
{{- $labels := $stack.vmagent.spec.podMetadata.labels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmagent-network-policy
spec:
  selector: >-
    app.simcore.io/name == "{{ index $labels "app.simcore.io/name" }}"
    && app.simcore.io/part-of == "{{ index $labels "app.simcore.io/part-of" }}"
  types: # calico only defaults this on create, so it must be explicit
    - Ingress
    - Egress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $stack.vmagent.spec.port }}
  egress:
    - action: Allow
      destination:
        nets:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
