{{- $stack := index .Values "vm-k8s-stack" -}}
{{- if dig "vmagent" "enabled" false $stack }}

{{- $labels := $stack.vmagent.spec.podMetadata.labels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmagent-scraper-network-policy
spec:
  selector: app == "{{ $labels.app }}" && part-of == "{{ index $labels "part-of" }}"
  egress:
    # scrape targets (kubelet, node-exporter, kube-state-metrics),
    # api server discovery (:6443) and remote-write to vmsingle
    - action: Allow
      destination:
        nets:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
{{- end }}
