{{- $stack := index .Values "vm-k8s-stack" -}}
{{- $labels := $stack.vmalert.spec.podMetadata.labels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmalert-network-policy
spec:
  selector: >-
    app.simcore.io/name == "{{ index $labels "app.simcore.io/name" }}"
    && app.simcore.io/part-of == "{{ index $labels "app.simcore.io/part-of" }}"
  types: # calico only defaults this on create, so it must be explicit
    - Ingress
    - Egress
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $stack.vmalert.spec.port }}
  egress:
    {{- if dig "vmsingle" "enabled" false $stack }}
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $stack.vmsingle.spec.port }}
    {{- else }}
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $stack.vmcluster.spec.vmselect.port }}
          - {{ $stack.vmcluster.spec.vminsert.port }}
    {{- end }}
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ .Values.kubernetesApiServerPort }}
