{{- $stack := index .Values "vm-k8s-stack" -}}
{{- if dig "vmsingle" "enabled" false $stack }}

{{- $labels := $stack.vmsingle.spec.podMetadata.labels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmsingle-network-policy
spec:
  selector: app == "{{ $labels.app }}" && part-of == "{{ index $labels "part-of" }}"
  ingress:
    # writes from vmagent and reads from traefik (via ingress)
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $stack.vmsingle.spec.port }}
{{- end }}
