{{- $stack := index .Values "vm-k8s-stack" -}}
{{- if dig "vmsingle" "enabled" false $stack }}

{{- $labels := $stack.vmsingle.spec.podMetadata.labels }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmsingle-network-policy
spec:
  selector: >-
    app.simcore.io/name == "{{ index $labels "app.simcore.io/name" }}"
    && app.simcore.io/part-of == "{{ index $labels "app.simcore.io/part-of" }}"
  ingress:
    # writes from vmagent and reads from traefik (via ingress)
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ $stack.vmsingle.spec.port }}
  {{- if dig "vmalert" "enabled" false $stack }}
  egress:
    # proxy vmalert UI/API (-vmalert.proxyURL) to vmalert
    - action: Allow
      protocol: TCP
      destination:
        selector: >-
          app.simcore.io/name == "{{ index $stack.vmalert.spec.podMetadata.labels "app.simcore.io/name" }}"
          && app.simcore.io/part-of == "{{ index $stack.vmalert.spec.podMetadata.labels "app.simcore.io/part-of" }}"
        ports:
          - {{ $stack.vmalert.spec.port }}
  {{- end }}
{{- end }}
