version: '3.8'
configs:
  maintenance_page_web_html:
    file: ./page/web/index.html
  maintenance_page_api_html:
    file: ./page/api/index.html
  nginx_config:
    file: ./nginx-config/default.conf
services:
  maintenance_page_web:
    configs:
      - source: maintenance_page_web_html
        target: /usr/share/nginx/html/index.html
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    # nginx config
    image: nginx:1.23.3
    networks:
      - public
      - monitored
    deploy:
      labels:
          - traefik.enable=true
          - traefik.docker.network=${PUBLIC_NETWORK}
          - traefik.http.routers.nginx_web.priority=2
          - traefik.http.routers.nginx_web.rule=${DEPLOYMENT_FQDNS_CAPTURE_TRAEFIK_RULE_CATCHALL}
          # Todo: Capture Host(`${DEPLOYMENT_FQDN}/study/*`)
          - traefik.http.routers.nginx_web.tls=true
          - traefik.http.routers.nginx_web.tls.certresolver=myresolver
          - traefik.http.services.nginx_web.loadbalancer.server.port=80
          - traefik.http.routers.nginx_web.entrypoints=https
  maintenance_page_api:
    # nginx config
    image: nginx:1.23.3
    configs:
      - source: maintenance_page_api_html
        target: /usr/share/nginx/html/index.html
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    networks:
      - public
      - monitored
    deploy:
      labels:
          - traefik.enable=true
          - traefik.docker.network=${PUBLIC_NETWORK}
          - traefik.http.routers.nginx_api.priority=2
          - traefik.http.routers.nginx_api.tls=true
          - traefik.http.routers.nginx_api.rule=${DEPLOYMENT_API_DOMAIN_CAPTURE_TRAEFIK_RULE}
          - traefik.http.routers.nginx_api.tls.certresolver=myresolver
          - traefik.http.services.nginx_api.loadbalancer.server.port=80
          - traefik.http.routers.nginx_api.entrypoints=https
networks:
  public:
    external: true
    name: ${PUBLIC_NETWORK}
  monitored:
    name: ${MONITORED_NETWORK}
    external: true
