version: '3.7'
services:
  grafana:
    deploy:
      placement:
        constraints:
          - node.labels.grafana==true
  prometheuscatchall:
    deploy:
      placement:
        constraints:
  prometheusfederation:
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
