version: "3.7"
services:
  prometheus:
    deploy:
      labels:
        - traefik.http.routers.prometheus.tls.certresolver=lehttpchallenge

  grafana:
    deploy:
      labels:
        - traefik.http.routers.grafana.tls.certresolver=lehttpchallenge
