version: "3.7"

volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}

networks:
  internal:
    driver: overlay
    attachable: true
  monitored:
    name: ${MONITORED_NETWORK}
    external: true
  public:
    external: true
    name: ${PUBLIC_NETWORK}

configs:
  alertmanager_config:
    file: ./alertmanager/config.yml
  node_exporter_entrypoint:
    file: ./node-exporter/docker-entrypoint.sh
  prometheus_config:
    file: ./prometheus/prometheus.yml
  prometheus_rules:
    file: ./prometheus/prometheus.rules.yml
  grafana_image_renderer_config:
    file: ./grafana-image-renderer/config.json
services:
  prometheus:
    image: prom/prometheus:v2.38.0
    volumes:
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root # only user root can use the docker socket
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus_rules
        target: /etc/prometheus/prometheus.rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=${PROMETHEUS_RETENTION}"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.external-url=https://${MONITORING_DOMAIN}/prometheus/"
      - "--web.route-prefix=/"
      - "--storage.tsdb.allow-overlapping-blocks" # via https://jessicagreben.medium.com/prometheus-fill-in-data-for-new-recording-rules-30a14ccb8467
      #- "--web.enable-admin-api" This allows messing with prometheus using its API from the CLI. Disabled for security reasons by default.
    networks:
      - internal
      - monitored
      - public
    extra_hosts: []
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${PUBLIC_NETWORK}
        # direct access through port
        - traefik.http.services.prometheus.loadbalancer.server.port=${PROMETHEUS_PORT}
        - traefik.http.routers.prometheus.rule=Host(`${MONITORING_DOMAIN}`) && PathPrefix(`/prometheus`)
        - traefik.http.routers.prometheus.entrypoints=https
        - traefik.http.routers.prometheus.tls=true
        - traefik.http.middlewares.prometheus_stripprefixregex.stripprefixregex.regex=^/prometheus
        - traefik.http.routers.prometheus.middlewares=ops_whitelist_ips@docker, ops_auth@docker, ops_gzip@docker, prometheus_stripprefixregex
        - prometheus-job=prometheus
        - prometheus-port=${PROMETHEUS_PORT}
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 64M

  node-exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /etc/hostname:/etc/nodename # doesn't work with windows
    configs:
      - source: node_exporter_entrypoint
        target: /docker-entrypoint.sh
    environment:
      - NODE_ID={{.Node.ID}}
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.textfile.directory=/home/"
      - "--collector.meminfo_numa"
      - "--no-collector.ipvs"
    entrypoint:
      - /bin/sh
      - /docker-entrypoint.sh
    networks:
      - internal
      - monitored
    deploy:
      labels:
        - prometheus-job=node-exporter
        - prometheus-port=9100
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  nvidia-exporter:
    image: mindprince/nvidia_gpu_prometheus_exporter:0.1
    networks:
      - internal
      - monitored
    deploy:
      labels:
        - prometheus-job=nvidia-exporter
        - prometheus-port=9445
      placement:
        constraints:
          - node.labels.gpu==true
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  alertmanager:
    image: prom/alertmanager:v0.20.0
    volumes:
      - alertmanager_data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    networks:
      - internal
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/config.yml
    deploy:
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  cadvisor-exporter:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - internal
      - monitored
    command: --logtostderr --docker_only --allow_dynamic_housekeeping=true
    deploy:
      labels:
        - prometheus-job=cadvisor
        - prometheus-port=8080
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  grafana:
    image: grafana/grafana-oss:9.1.3
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./grafana/config.monitoring
    user: "104"
    networks:
      - internal
      - monitored # needed to access postgres
      - public
    deploy:
      #restart_policy:
      #  condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=${PUBLIC_NETWORK}
        # direct access through port
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.rule=Host(`${MONITORING_DOMAIN}`) && PathPrefix(`/grafana`)
        - traefik.http.routers.grafana.entrypoints=https
        - traefik.http.routers.grafana.tls=true
        - traefik.http.middlewares.grafana_replace_regex.replacepathregex.regex=^/grafana/?(.*)$$
        - traefik.http.middlewares.grafana_replace_regex.replacepathregex.replacement=/$${1}
        - traefik.http.routers.grafana.middlewares=ops_whitelist_ips@docker, ops_gzip@docker, grafana_replace_regex
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  grafana-image-renderer:
    image: grafana/grafana-image-renderer:3.6.1
    configs:
      - source: grafana_image_renderer_config
        target: /usr/src/app/config.json
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M

  dcgm-exporter:
    cap_add:
      - SYS_ADMIN
    image: nvidia/dcgm-exporter:latest
    hostname: '{{.Node.Hostname}}'
    networks:
      - internal
      - monitored
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.gpu==true
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    labels:
      - prometheus-job=dcgm-exporter
      - prometheus-port=9400
