version: '3.7'
services:

  cadvisor-exporter:
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  grafana:
    dns: 9.9.9.9
    deploy:
      placement:
        constraints:
          - node.labels.grafana==true

  prometheuscatchall:
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true

  prometheusfederation:
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
