version: '3.7'
services:
  grafana:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.grafana==true

  prometheuscatchall:
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true

  prometheusfederation:
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
