version: "3.7"
services:
  prometheuscatchall:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
      resources:
        limits:
          memory: 24576M
        reservations:
          memory: 24576M
  prometheusfederation:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 4096M
  grafana:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.grafana==true
