version: "3.7"
services:
  prometheus-catchall:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
      resources:
        limits:
          memory: 24576M
        reservations:
          memory: 24576M
  prometheus-cadvisor:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 4096M
  grafana:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.grafana==true
  alertmanager:
    deploy:
      placement:
        constraints:
          - node.labels.grafana==true
  cadvisor-exporter:
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
