version: "3.7"
services:
  prometheuscatchall:
    deploy:
      labels:
        - traefik.http.routers.prometheuscatchall.tls.certresolver=lehttpchallenge
  grafana:
    deploy:
      labels:
        - traefik.http.routers.grafana.tls.certresolver=lehttpchallenge
  prometheusfederation:
    deploy:
      labels:
        - traefik.http.routers.prometheusfederation.tls.certresolver=lehttpchallenge
  # prometheuscadvisor:
  #   deploy:
  #     placement:
  #       constraints:
  #         - traefik.http.routers.prometheus.tls.certresolver=lehttpchallenge
