version: "3.7"
services:
  cadvisor-exporter:
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  prometheuscatchall:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
      resources:
        limits:
          memory: 24576M
  prometheusfederation:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
  grafana:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.grafana==true
