version: "3.7"
services:
  prometheus-catchall:
    deploy:
      labels:
        - traefik.http.routers.prometheus.tls.certresolver=lehttpchallenge
  grafana:
    deploy:
      labels:
        - traefik.http.routers.grafana.tls.certresolver=lehttpchallenge
  prometheus-cadvisor:
    deploy:
      placement:
        constraints:
          - traefik.http.routers.prometheus.tls.certresolver=lehttpchallenge
