version: '3.7'
services:
  grafana:
    deploy:
      placement:
        constraints:
          - node.labels.grafana==true
  prometheus:
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
