version: '3.7'
services:
  grafana:
    deploy:
      placement:
        constraints:
          - node.labels.grafana==true
  prometheus-catchall:
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
  prometheus-cadvisor:
    deploy:
      placement:
        constraints:
          - node.labels.prometheus==true
