version: "3.7"
services:
  prometheus-catchall:
    deploy:
      labels:
        - traefik.http.routers.prometheus.tls.certresolver=myresolver

  grafana:
    deploy:
      labels:
        - traefik.http.routers.grafana.tls.certresolver=myresolver

  prometheus-cadvisor:
    deploy:
      labels:
        - traefik.http.routers.prometheus.tls.certresolver=myresolver
